import { NextResponse } from "next/server";
import { db, execSql } from "@/lib/db";
import { requireAdmin } from "@/lib/auth";

export const dynamic = "force-dynamic";
export const maxDuration = 30;

// POST /api/db-create-tables — creates the WebsiteScan + DetectionRule tables.
export async function POST(req: Request) {
  const auth = requireAdmin(req);
  if (!auth.ok) return auth.response;

  const statements = [
    `DROP TABLE IF EXISTS "DetectionRule"`,
    `DROP TABLE IF EXISTS "WebsiteScan"`,
    `CREATE TABLE IF NOT EXISTS "WebsiteScan" (id TEXT PRIMARY KEY, url TEXT NOT NULL, email TEXT, status TEXT NOT NULL DEFAULT 'running', score INTEGER, "findingsCount" INTEGER NOT NULL DEFAULT 0, "criticalCount" INTEGER NOT NULL DEFAULT 0, "highCount" INTEGER NOT NULL DEFAULT 0, "mediumCount" INTEGER NOT NULL DEFAULT 0, "lowCount" INTEGER NOT NULL DEFAULT 0, findings TEXT NOT NULL DEFAULT '[]', "ipAddress" TEXT, "userAgent" TEXT, duration INTEGER, "completedAt" TIMESTAMPTZ, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
    `CREATE TABLE IF NOT EXISTS "DetectionRule" (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT, pattern TEXT NOT NULL, severity TEXT NOT NULL DEFAULT 'medium', cwe TEXT, language TEXT NOT NULL DEFAULT 'javascript', "autoGenerated" BOOLEAN NOT NULL DEFAULT FALSE, active BOOLEAN NOT NULL DEFAULT TRUE, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
    `CREATE INDEX IF NOT EXISTS idx_ws_created ON "WebsiteScan"("createdAt")`,
    `CREATE INDEX IF NOT EXISTS idx_ws_status ON "WebsiteScan"(status)`,
    `CREATE INDEX IF NOT EXISTS idx_dr_active ON "DetectionRule"(active)`,
    `CREATE INDEX IF NOT EXISTS idx_dr_autogen ON "DetectionRule"("autoGenerated")`,
  ];
  try {
    for (const stmt of statements) {
      await execSql(stmt);
    }
    return NextResponse.json({ ok: true, message: "Tables created successfully" });
  } catch (err) {
    return NextResponse.json({ error: err instanceof Error ? err.message : "unknown" }, { status: 500 });
  }
}
