"use client";

// Adversarial AI Self-Attack — full-screen Command-Center tab.
//
// An AI agent whose only job is to find blind spots in GuardianX's own
// detection. It generates synthetic vulnerable code that *should* be
// flagged, runs it through the existing scan logic, and if GuardianX
// misses any, auto-writes a new detection rule + saves it to the
// DetectionRule table.
//
// Layout:
//   Header     → "ADVERSARIAL AI" + pulsing red dot + SELF-ATTACKING badge
//   Hero       → Big "Run Self-Attack" button + miss-rate stat tiles
//   Terminal   → animated per-snippet PASS/FAIL log during a run
//   Summary    → Tested N · Missed M · Rules Added K + new rules list
//   Rules      → Activate/Deactivate toggle for every auto-generated rule
//   History    → last 20 runs with miss rate + rules added per run
//
// Dark theme, red/emerald accents, hud-corners, NO indigo/blue. Mobile-first.

import { useCallback, useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Activity,
  AlertOctagon,
  Brain,
  Bug,
  CheckCircle2,
  Crosshair,
  Loader2,
  Play,
  Plus,
  Power,
  RefreshCw,
  ScrollText,
  ShieldAlert,
  Skull,
  XCircle,
  Zap,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Switch } from "@/components/ui/switch";

// ── Types (mirror the API route) ──────────────────────────────────────────
type Severity = "critical" | "high" | "medium" | "low";

interface RunRow {
  vulnId: string;
  vulnName: string;
  severity: Severity;
  cwe: string;
  language: string;
  detected: boolean;
  matchedRule?: string;
  snippet: string;
}

interface RuleAdded {
  id: string;
  name: string;
  severity: Severity;
  cwe: string | null;
  language: string;
}

interface SelfAttackResult {
  testedCount: number;
  missedCount: number;
  rulesAdded: RuleAdded[];
  report: string;
  runs: RunRow[];
  generatedAt: string;
}

interface HistoryRule {
  id?: string;
  name: string;
  severity: Severity;
  cwe: string | null;
  language: string;
}

interface SelfAttackRun {
  id: string;
  createdAt: string;
  actor: string;
  testedCount: number;
  missedCount: number;
  missRate: number;
  rulesAddedCount: number;
  rulesAdded: HistoryRule[];
  report: string;
}

interface DetectionRuleRow {
  id: string;
  name: string;
  description: string;
  pattern: string;
  severity: Severity;
  cwe: string | null;
  language: string;
  autoGenerated: boolean;
  isActive: boolean;
  hitsCount: number;
  createdAt: string;
}

interface RunsResponse {
  runs: SelfAttackRun[];
  rules: DetectionRuleRow[];
  totals: {
    totalRuns: number;
    totalTested: number;
    totalMissed: number;
    totalRulesAdded: number;
    avgMissRate: number;
    autoRulesActive: number;
    autoRulesTotal: number;
  };
}

// ── Color tokens (NO indigo/blue) ──────────────────────────────────────────
const SEVERITY_COLOR: Record<Severity, string> = {
  critical: "#ef4444", // red
  high: "#f43f5e",     // rose
  medium: "#f59e0b",   // amber
  low: "#10b981",      // emerald
};

const SEVERITY_LABEL: Record<Severity, string> = {
  critical: "CRIT",
  high: "HIGH",
  medium: "MED",
  low: "LOW",
};

// ── API helpers ────────────────────────────────────────────────────────────
function authHeaders(): HeadersInit {
  const token = typeof window !== "undefined" ? localStorage.getItem("guardianx-token") : null;
  return {
    "Content-Type": "application/json",
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  };
}

async function fetchRuns(signal: AbortSignal): Promise<RunsResponse> {
  const res = await fetch("/api/self-attack/runs", {
    credentials: "same-origin",
    headers: authHeaders(),
    signal,
  });
  const data = (await res.json().catch(() => ({}))) as RunsResponse & { error?: string };
  if (!res.ok) {
    throw new Error(data?.error ?? `Failed (${res.status})`);
  }
  return data;
}

async function postSelfAttack(signal: AbortSignal): Promise<SelfAttackResult> {
  const res = await fetch("/api/self-attack", {
    method: "POST",
    credentials: "same-origin",
    headers: authHeaders(),
    body: JSON.stringify({}),
    signal,
  });
  const data = (await res.json().catch(() => ({}))) as SelfAttackResult & { error?: string };
  if (!res.ok) {
    throw new Error(data?.error ?? `Self-attack failed (${res.status})`);
  }
  return data;
}

async function patchRuleToggle(ruleId: string, isActive: boolean): Promise<void> {
  const res = await fetch("/api/self-attack/runs", {
    method: "PATCH",
    credentials: "same-origin",
    headers: authHeaders(),
    body: JSON.stringify({ ruleId, isActive }),
  });
  if (!res.ok) {
    const data = await res.json().catch(() => ({})) as { error?: string };
    throw new Error(data?.error ?? `Failed (${res.status})`);
  }
}

// ── Count-up hook (animated number ticker) ──────────────────────────────────
function useCountUp(target: number, durationMs = 900): number {
  const [value, setValue] = useState(0);
  const rafRef = useRef<number | null>(null);
  const startRef = useRef<number | null>(null);
  const fromRef = useRef(0);

  useEffect(() => {
    fromRef.current = value;
    startRef.current = null;
    if (rafRef.current) cancelAnimationFrame(rafRef.current);
    const tick = (ts: number) => {
      if (startRef.current === null) startRef.current = ts;
      const elapsed = ts - startRef.current;
      const t = Math.min(1, elapsed / durationMs);
      const eased = 1 - Math.pow(1 - t, 3);
      setValue(Math.round(fromRef.current + (target - fromRef.current) * eased));
      if (t < 1) rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
    };
  }, [target, durationMs]);

  return value;
}

// ── Component ──────────────────────────────────────────────────────────────
export function AdversarialAI() {
  // History + rule list (fetched on mount).
  const [history, setHistory] = useState<RunsResponse | null>(null);
  const [historyLoading, setHistoryLoading] = useState(true);
  const [historyError, setHistoryError] = useState<string | null>(null);

  // Active run state.
  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<SelfAttackResult | null>(null);

  // Animated terminal lines (revealed one by one while the API runs).
  const [terminalLines, setTerminalLines] = useState<RunRow[]>([]);
  const [terminalPhase, setTerminalPhase] = useState<string>("");

  // Auto-scroll the terminal to the bottom when new lines arrive.
  const terminalRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    if (terminalRef.current) {
      terminalRef.current.scrollTop = terminalRef.current.scrollHeight;
    }
  }, [terminalLines, terminalPhase]);

  // ── Load history ────────────────────────────────────────────────────────
  const loadHistory = useCallback(async () => {
    setHistoryLoading(true);
    setHistoryError(null);
    const ac = new AbortController();
    try {
      const data = await fetchRuns(ac.signal);
      setHistory(data);
    } catch (e) {
      if ((e as Error).name !== "AbortError") {
        setHistoryError((e as Error).message ?? "Failed to load history.");
      }
    } finally {
      setHistoryLoading(false);
    }
  }, []);

  useEffect(() => {
    loadHistory();
  }, [loadHistory]);

  // ── Run self-attack ──────────────────────────────────────────────────────
  const handleRun = useCallback(async () => {
    if (running) return;
    setRunning(true);
    setError(null);
    setResult(null);
    setTerminalLines([]);
    setTerminalPhase("Initializing adversarial AI core...");

    const ac = new AbortController();

    // Simulated phase ticker — gives the terminal a "live" feel while the
    // API call (which may take 5-15s for multiple LLM calls) is in flight.
    const phases = [
      "Initializing adversarial AI core...",
      "Loading 24-pattern vuln library...",
      "Selecting 5-10 synthetic snippets for this run...",
      "Running each snippet through GuardianX's existing scan logic...",
      "Identifying false negatives...",
      "Generating new detection rules via LLM...",
      "Persisting rules to DetectionRule table...",
      "Auditing run for history...",
    ];
    let phaseIdx = 0;
    const phaseTimer = setInterval(() => {
      phaseIdx = Math.min(phases.length - 1, phaseIdx + 1);
      setTerminalPhase(phases[phaseIdx] ?? "");
    }, 900);

    try {
      const res = await postSelfAttack(ac.signal);

      // Reveal each run row one-by-one (with a PASS/FAIL badge).
      setTerminalPhase(`Analyzing ${res.runs.length} test snippets...`);
      const reveal: RunRow[] = [];
      for (let i = 0; i < res.runs.length; i++) {
        reveal.push(res.runs[i]);
        setTerminalLines([...reveal]);
        // Small stagger so the terminal types out visibly.
        await new Promise((r) => setTimeout(r, 180));
      }
      setTerminalPhase("Run complete.");
      setResult(res);

      // Refresh history + rules list.
      await loadHistory();
    } catch (e) {
      if ((e as Error).name !== "AbortError") {
        setError((e as Error).message ?? "Self-attack failed.");
      }
    } finally {
      clearInterval(phaseTimer);
      setRunning(false);
    }
  }, [running, loadHistory]);

  // ── Toggle rule active state ─────────────────────────────────────────────
  const handleToggleRule = useCallback(async (ruleId: string, isActive: boolean) => {
    // Optimistic update.
    setHistory((prev) => {
      if (!prev) return prev;
      const updated = prev.rules.map((r) =>
        r.id === ruleId ? { ...r, isActive } : r,
      );
      const activeCount = updated.filter((r) => r.isActive).length;
      return {
        ...prev,
        rules: updated,
        totals: {
          ...prev.totals,
          autoRulesActive: activeCount,
        },
      };
    });
    try {
      await patchRuleToggle(ruleId, isActive);
    } catch (e) {
      // Revert on failure.
      setHistory((prev) => {
        if (!prev) return prev;
        const reverted = prev.rules.map((r) =>
          r.id === ruleId ? { ...r, isActive: !isActive } : r,
        );
        const activeCount = reverted.filter((r) => r.isActive).length;
        return {
          ...prev,
          rules: reverted,
          totals: { ...prev.totals, autoRulesActive: activeCount },
        };
      });
      setError((e as Error).message ?? "Failed to toggle rule.");
    }
  }, []);

  // ── Animated totals ───────────────────────────────────────────────────────
  const testedAnim = useCountUp(result?.testedCount ?? 0);
  const missedAnim = useCountUp(result?.missedCount ?? 0);
  const rulesAnim = useCountUp(result?.rulesAdded.length ?? 0);

  return (
    <div className="flex h-full w-full flex-col gap-4 overflow-y-auto p-3 sm:gap-6 sm:p-6">
      {/* ── Header ──────────────────────────────────────────────────────── */}
      <header className="holo-card-sharp hud-corners neon-border-red relative flex flex-wrap items-center justify-between gap-3 overflow-hidden rounded-xl bg-zinc-950/80 p-4 sm:p-5">
        <div className="flex items-center gap-3">
          <div className="relative flex size-11 items-center justify-center rounded-md border border-red-500/40 bg-red-500/10">
            <Skull className="size-5 text-red-400" />
            <span
              className={`pulse-dot absolute -right-0.5 -top-0.5 size-2.5 rounded-full bg-red-500 ${running ? "" : "opacity-70"}`}
              style={running ? { boxShadow: "0 0 0 0 rgba(239,68,68,0.7)" } : undefined}
            />
          </div>
          <div>
            <h1 className="neon-red font-mono text-base font-bold uppercase tracking-widest sm:text-xl">
              Adversarial AI
            </h1>
            <p className="text-[11px] text-zinc-500 sm:text-xs">
              Self-attacking red team · finds blind spots in GuardianX's own detection
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <AnimatePresence mode="wait">
            {running ? (
              <motion.div
                key="self-attacking"
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.8 }}
                className="flex items-center gap-2 rounded-full border border-red-500/60 bg-red-500/10 px-3 py-1.5"
              >
                <span className="relative flex size-2">
                  <span className="absolute inline-flex size-full animate-ping rounded-full bg-red-500 opacity-75" />
                  <span className="relative inline-flex size-2 rounded-full bg-red-500" />
                </span>
                <span className="neon-red font-mono text-[10px] font-bold uppercase tracking-widest sm:text-[11px]">
                  Self-Attacking
                </span>
              </motion.div>
            ) : (
              <motion.div
                key="standby"
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.8 }}
                className="flex items-center gap-2 rounded-full border border-emerald-500/40 bg-emerald-500/5 px-3 py-1.5"
              >
                <span className="size-2 rounded-full bg-emerald-400" />
                <span className="font-mono text-[10px] font-bold uppercase tracking-widest text-emerald-400 sm:text-[11px]">
                  Standby
                </span>
              </motion.div>
            )}
          </AnimatePresence>
          <Button
            variant="outline"
            size="sm"
            onClick={loadHistory}
            disabled={historyLoading}
            className="border-zinc-700 bg-zinc-900/60 font-mono text-[11px] text-zinc-300 hover:bg-zinc-800 hover:text-zinc-100"
          >
            <RefreshCw className={`size-3.5 ${historyLoading ? "animate-spin" : ""}`} />
            <span className="hidden sm:inline">REFRESH</span>
          </Button>
        </div>
      </header>

      {/* ── Run control + stat tiles ─────────────────────────────────────── */}
      <section className="grid grid-cols-1 gap-4 lg:grid-cols-3">
        {/* Run button tile */}
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ type: "spring", stiffness: 180, damping: 22 }}
          className="holo-card-sharp hud-corners relative flex flex-col justify-between gap-4 overflow-hidden rounded-xl bg-zinc-950/80 p-5"
        >
          <div className="flex items-center gap-2">
            <Crosshair className="size-4 text-red-400" />
            <span className="font-mono text-[11px] uppercase tracking-widest text-zinc-400">
              Run Self-Attack
            </span>
          </div>
          <div>
            <h2 className="font-mono text-lg font-bold text-zinc-100">
              {running ? "Attacking GuardianX..." : "Find blind spots"}
            </h2>
            <p className="mt-1 text-xs text-zinc-500">
              The adversarial AI generates 5-10 synthetic vulnerable snippets, scans each
              one through the existing detection logic, and auto-writes a new
              DetectionRule for every miss.
            </p>
          </div>
          <Button
            onClick={handleRun}
            disabled={running}
            className="group relative w-full overflow-hidden rounded-md border border-red-500/60 bg-gradient-to-r from-red-500/20 via-rose-500/10 to-red-500/20 font-mono text-[12px] font-bold uppercase tracking-widest text-red-300 transition-all hover:from-red-500/30 hover:to-red-500/30 hover:text-red-200 disabled:opacity-60"
          >
            {running ? (
              <>
                <Loader2 className="size-4 animate-spin" />
                RUNNING
              </>
            ) : (
              <>
                <Play className="size-4 transition-transform group-hover:scale-110" />
                Run Self-Attack
              </>
            )}
          </Button>
        </motion.div>

        {/* Stat tiles */}
        <StatTile
          label="Snippets Tested"
          value={testedAnim}
          icon={<Bug className="size-4" />}
          color="#06b6d4"
          hint={result ? `last run: ${new Date(result.generatedAt).toLocaleString()}` : "no runs yet"}
        />
        <StatTile
          label="Missed (False Negatives)"
          value={missedAnim}
          icon={<XCircle className="size-4" />}
          color="#ef4444"
          hint={result && result.testedCount > 0
            ? `${Math.round((result.missedCount / result.testedCount) * 100)}% miss rate`
            : "—"}
        />
      </section>

      {/* ── Terminal ──────────────────────────────────────────────────────── */}
      <section className="holo-card-sharp hud-corners relative overflow-hidden rounded-xl bg-zinc-950/90 p-0">
        <div className="flex items-center justify-between border-b border-red-500/20 bg-red-500/5 px-4 py-2.5">
          <div className="flex items-center gap-2">
            <ScrollText className="size-4 text-red-400" />
            <span className="font-mono text-[11px] uppercase tracking-widest text-red-400">
              Adversarial Terminal
            </span>
          </div>
          <div className="flex items-center gap-1.5">
            <span className="size-2.5 rounded-full bg-red-500/70" />
            <span className="size-2.5 rounded-full bg-amber-500/70" />
            <span className="size-2.5 rounded-full bg-emerald-500/70" />
          </div>
        </div>
        <div
          ref={terminalRef}
          className="max-h-[400px] min-h-[200px] overflow-y-auto p-4 font-mono text-[11px] leading-relaxed sm:text-xs"
        >
          {error ? (
            <div className="flex items-start gap-2 text-rose-300">
              <AlertOctagon className="mt-0.5 size-4 shrink-0 text-rose-400" />
              <div>
                <span className="font-bold text-rose-400">RUN FAILED</span>
                <p className="mt-1 text-zinc-400">{error}</p>
              </div>
            </div>
          ) : running || terminalLines.length > 0 || result ? (
            <div className="flex flex-col gap-1.5">
              <div className="text-zinc-500">
                <span className="text-emerald-400">$</span> guardianx self-attack --run
              </div>
              <div className="text-zinc-500">
                <span className="text-emerald-400">→</span> {terminalPhase}
              </div>
              <div className="mt-2 flex flex-col gap-1.5">
                <AnimatePresence initial={false}>
                  {terminalLines.map((row, idx) => (
                    <motion.div
                      key={`${row.vulnId}-${idx}`}
                      initial={{ opacity: 0, x: -8 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ type: "spring", stiffness: 220, damping: 22 }}
                      className="flex flex-wrap items-center gap-2"
                    >
                      <span className="text-zinc-600">[{String(idx + 1).padStart(2, "0")}]</span>
                      <span className="text-zinc-300">{row.vulnName}</span>
                      <span className="text-zinc-600">·</span>
                      <span
                        className="rounded px-1 text-[9px] font-bold uppercase sm:text-[10px]"
                        style={{
                          color: SEVERITY_COLOR[row.severity],
                          background: `${SEVERITY_COLOR[row.severity]}22`,
                          border: `1px solid ${SEVERITY_COLOR[row.severity]}55`,
                        }}
                      >
                        {SEVERITY_LABEL[row.severity]}
                      </span>
                      <span className="text-zinc-600">·</span>
                      <span className="text-zinc-500">{row.cwe}</span>
                      <span className="ml-auto">
                        {row.detected ? (
                          <span className="flex items-center gap-1 text-emerald-400">
                            <CheckCircle2 className="size-3" />
                            <span className="text-[10px] font-bold uppercase sm:text-[11px]">PASS</span>
                          </span>
                        ) : (
                          <span className="flex items-center gap-1 text-rose-400">
                            <XCircle className="size-3" />
                            <span className="text-[10px] font-bold uppercase sm:text-[11px]">FAIL</span>
                          </span>
                        )}
                      </span>
                    </motion.div>
                  ))}
                </AnimatePresence>
              </div>
              {running && (
                <div className="mt-2 flex items-center gap-2 text-zinc-500">
                  <span className="text-emerald-400">▌</span>
                  <Loader2 className="size-3 animate-spin" />
                  <span className="text-zinc-500">awaiting response...</span>
                </div>
              )}
              {result && !running && (
                <div className="mt-2 text-emerald-400">
                  <span>✓</span> Run complete — {result.testedCount} tested, {result.missedCount} missed, {result.rulesAdded.length} rule(s) added.
                </div>
              )}
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center gap-3 py-10 text-center text-zinc-600">
              <Brain className="size-7 text-zinc-700" />
              <p className="text-xs">
                No runs yet. Click <span className="text-red-400">RUN SELF-ATTACK</span> to begin.
              </p>
            </div>
          )}
        </div>
      </section>

      {/* ── Summary card + new rules ─────────────────────────────────────── */}
      <AnimatePresence>
        {result && !running && (
          <motion.section
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -12 }}
            transition={{ type: "spring", stiffness: 160, damping: 20 }}
            className="holo-card-sharp hud-corners relative overflow-hidden rounded-xl bg-zinc-950/80 p-4 sm:p-6"
          >
            <div className="mb-4 flex items-center gap-2">
              <Activity className="size-4 text-emerald-400" />
              <span className="font-mono text-[11px] uppercase tracking-widest text-emerald-400">
                Run Summary
              </span>
            </div>
            <div className="grid grid-cols-3 gap-3">
              <SummaryStat label="Tested" value={result.testedCount} color="#06b6d4" />
              <SummaryStat label="Missed" value={result.missedCount} color="#ef4444" />
              <SummaryStat label="Rules Added" value={result.rulesAdded.length} color="#10b981" />
            </div>
            {result.report && (
              <p className="mt-4 rounded-md border border-zinc-800 bg-zinc-900/60 p-3 text-xs leading-relaxed text-zinc-400">
                {result.report}
              </p>
            )}
            {result.rulesAdded.length > 0 && (
              <div className="mt-4">
                <div className="mb-2 flex items-center gap-2">
                  <Plus className="size-3.5 text-emerald-400" />
                  <span className="font-mono text-[11px] uppercase tracking-widest text-emerald-400">
                    New Detection Rules
                  </span>
                </div>
                <div className="flex flex-col gap-2">
                  {result.rulesAdded.map((r) => (
                    <motion.div
                      key={r.id}
                      initial={{ opacity: 0, x: 12 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ type: "spring", stiffness: 200, damping: 22 }}
                      className="flex flex-wrap items-center gap-2 rounded-md border border-zinc-800 bg-zinc-900/60 px-3 py-2"
                    >
                      <span
                        className="rounded px-1.5 py-0.5 font-mono text-[10px] font-bold uppercase"
                        style={{
                          color: SEVERITY_COLOR[r.severity],
                          background: `${SEVERITY_COLOR[r.severity]}22`,
                          border: `1px solid ${SEVERITY_COLOR[r.severity]}55`,
                        }}
                      >
                        {SEVERITY_LABEL[r.severity]}
                      </span>
                      <span className="font-mono text-xs text-zinc-200">{r.name}</span>
                      <span className="font-mono text-[10px] text-zinc-500">{r.cwe ?? "—"}</span>
                      <Badge
                        variant="outline"
                        className="ml-auto border-emerald-500/40 bg-emerald-500/5 font-mono text-[10px] text-emerald-400"
                      >
                        {r.language}
                      </Badge>
                    </motion.div>
                  ))}
                </div>
              </div>
            )}
          </motion.section>
        )}
      </AnimatePresence>

      {/* ── Auto-generated rules with toggle ─────────────────────────────── */}
      <section className="holo-card-sharp hud-corners relative overflow-hidden rounded-xl bg-zinc-950/80 p-4 sm:p-6">
        <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <ShieldAlert className="size-4 text-amber-400" />
            <span className="font-mono text-[11px] uppercase tracking-widest text-amber-400">
              Auto-Generated Detection Rules
            </span>
          </div>
          {history && (
            <div className="flex items-center gap-2 font-mono text-[11px] text-zinc-500">
              <span className="text-emerald-400">{history.totals.autoRulesActive}</span>
              <span className="text-zinc-600">/</span>
              <span>{history.totals.autoRulesTotal}</span>
              <span className="ml-1 text-zinc-600">active</span>
            </div>
          )}
        </div>
        {historyError ? (
          <div className="rounded-md border border-rose-500/30 bg-rose-500/5 p-4 text-xs text-rose-300">
            Failed to load rules: {historyError}
          </div>
        ) : historyLoading && !history ? (
          <div className="flex flex-col gap-2">
            {Array.from({ length: 3 }).map((_, i) => (
              <Skeleton key={i} className="h-14 w-full rounded-md bg-zinc-800/60" />
            ))}
          </div>
        ) : history && history.rules.length > 0 ? (
          <div className="flex flex-col gap-2">
            {history.rules.map((rule) => (
              <RuleRow key={rule.id} rule={rule} onToggle={handleToggleRule} />
            ))}
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center gap-3 py-8 text-center text-zinc-600">
            <Zap className="size-6 text-zinc-700" />
            <p className="text-xs">
              No auto-generated rules yet. Run a self-attack to populate this list.
            </p>
          </div>
        )}
      </section>

      {/* ── History table ─────────────────────────────────────────────────── */}
      <section className="holo-card-sharp hud-corners relative overflow-hidden rounded-xl bg-zinc-950/80 p-4 sm:p-6">
        <div className="mb-4 flex items-center gap-2">
          <ScrollText className="size-4 text-cyan-400" />
          <span className="font-mono text-[11px] uppercase tracking-widest text-cyan-400">
            Run History (Last 20)
          </span>
        </div>
        {historyError ? (
          <div className="rounded-md border border-rose-500/30 bg-rose-500/5 p-4 text-xs text-rose-300">
            Failed to load history: {historyError}
          </div>
        ) : historyLoading && !history ? (
          <div className="flex flex-col gap-2">
            {Array.from({ length: 4 }).map((_, i) => (
              <Skeleton key={i} className="h-12 w-full rounded-md bg-zinc-800/60" />
            ))}
          </div>
        ) : history && history.runs.length > 0 ? (
          <>
            {/* Desktop table */}
            <div className="hidden overflow-x-auto md:block">
              <table className="w-full border-collapse font-mono text-xs">
                <thead>
                  <tr className="border-b border-zinc-800 text-left text-[10px] uppercase tracking-widest text-zinc-500">
                    <th className="px-3 py-2 font-bold">Date</th>
                    <th className="px-3 py-2 font-bold">Actor</th>
                    <th className="px-3 py-2 text-right font-bold">Tested</th>
                    <th className="px-3 py-2 text-right font-bold">Missed</th>
                    <th className="px-3 py-2 text-right font-bold">Miss %</th>
                    <th className="px-3 py-2 text-right font-bold">Rules Added</th>
                  </tr>
                </thead>
                <tbody>
                  {history.runs.map((run, idx) => (
                    <motion.tr
                      key={run.id}
                      initial={{ opacity: 0, y: 4 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: Math.min(idx * 0.03, 0.3) }}
                      className="border-b border-zinc-900 text-zinc-300"
                    >
                      <td className="px-3 py-2 text-zinc-400">
                        {new Date(run.createdAt).toLocaleString()}
                      </td>
                      <td className="px-3 py-2 text-zinc-500">{run.actor}</td>
                      <td className="px-3 py-2 text-right text-cyan-400">{run.testedCount}</td>
                      <td className="px-3 py-2 text-right text-rose-400">{run.missedCount}</td>
                      <td className="px-3 py-2 text-right">
                        <span
                          className="rounded px-1.5 py-0.5 text-[10px] font-bold"
                          style={{
                            color: run.missRate > 50 ? "#ef4444" : run.missRate > 25 ? "#f59e0b" : "#10b981",
                            background: run.missRate > 50 ? "rgba(239,68,68,0.15)" : run.missRate > 25 ? "rgba(245,158,11,0.15)" : "rgba(16,185,129,0.15)",
                          }}
                        >
                          {run.missRate}%
                        </span>
                      </td>
                      <td className="px-3 py-2 text-right text-emerald-400">{run.rulesAddedCount}</td>
                    </motion.tr>
                  ))}
                </tbody>
              </table>
            </div>
            {/* Mobile cards */}
            <div className="flex flex-col gap-2 md:hidden">
              {history.runs.map((run) => (
                <div
                  key={run.id}
                  className="rounded-md border border-zinc-800 bg-zinc-900/60 p-3"
                >
                  <div className="flex items-center justify-between gap-2">
                    <span className="font-mono text-[11px] text-zinc-400">
                      {new Date(run.createdAt).toLocaleString()}
                    </span>
                    <span
                      className="rounded px-1.5 py-0.5 text-[10px] font-bold"
                      style={{
                        color: run.missRate > 50 ? "#ef4444" : run.missRate > 25 ? "#f59e0b" : "#10b981",
                        background: run.missRate > 50 ? "rgba(239,68,68,0.15)" : run.missRate > 25 ? "rgba(245,158,11,0.15)" : "rgba(16,185,129,0.15)",
                      }}
                    >
                      {run.missRate}%
                    </span>
                  </div>
                  <div className="mt-2 flex items-center gap-3 font-mono text-[11px]">
                    <span className="text-cyan-400">{run.testedCount} tested</span>
                    <span className="text-rose-400">{run.missedCount} missed</span>
                    <span className="text-emerald-400">{run.rulesAddedCount} rules</span>
                  </div>
                  <p className="mt-1 truncate font-mono text-[10px] text-zinc-500">
                    by {run.actor}
                  </p>
                </div>
              ))}
            </div>
          </>
        ) : (
          <div className="flex flex-col items-center justify-center gap-3 py-8 text-center text-zinc-600">
            <ScrollText className="size-6 text-zinc-700" />
            <p className="text-xs">No runs yet — click RUN SELF-ATTACK to begin.</p>
          </div>
        )}
      </section>

      <div className="flex-1" />
    </div>
  );
}

// ── Stat tile (hero) ───────────────────────────────────────────────────────
function StatTile({
  label,
  value,
  icon,
  color,
  hint,
}: {
  label: string;
  value: number;
  icon: React.ReactNode;
  color: string;
  hint: string;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ type: "spring", stiffness: 180, damping: 22 }}
      className="holo-card-sharp hud-corners relative flex flex-col gap-2 overflow-hidden rounded-xl bg-zinc-950/80 p-5"
    >
      <div className="flex items-center justify-between">
        <span className="font-mono text-[11px] uppercase tracking-widest text-zinc-400">
          {label}
        </span>
        <span style={{ color }}>{icon}</span>
      </div>
      <span
        className="font-mono text-3xl font-bold tabular-nums sm:text-4xl"
        style={{
          color,
          textShadow: `0 0 12px ${color}80, 0 0 24px ${color}40`,
        }}
      >
        {value}
      </span>
      <span className="font-mono text-[10px] text-zinc-600">{hint}</span>
    </motion.div>
  );
}

// ── Summary stat (smaller, inside summary card) ───────────────────────────
function SummaryStat({ label, value, color }: { label: string; value: number; color: string }) {
  return (
    <div
      className="rounded-md border p-3 text-center"
      style={{
        borderColor: `${color}40`,
        background: `${color}10`,
      }}
    >
      <div className="font-mono text-[10px] uppercase tracking-widest text-zinc-400">
        {label}
      </div>
      <div
        className="mt-1 font-mono text-2xl font-bold tabular-nums sm:text-3xl"
        style={{ color, textShadow: `0 0 8px ${color}80` }}
      >
        {value}
      </div>
    </div>
  );
}

// ── Rule row with activate/deactivate toggle ──────────────────────────────
function RuleRow({
  rule,
  onToggle,
}: {
  rule: DetectionRuleRow;
  onToggle: (ruleId: string, isActive: boolean) => Promise<void>;
}) {
  const [toggling, setToggling] = useState(false);
  const color = SEVERITY_COLOR[rule.severity] ?? "#a1a1aa";

  const handleToggle = useCallback(async () => {
    setToggling(true);
    try {
      await onToggle(rule.id, !rule.isActive);
    } finally {
      setToggling(false);
    }
  }, [rule.id, rule.isActive, onToggle]);

  return (
    <motion.div
      layout
      className="flex flex-wrap items-center gap-2 rounded-md border border-zinc-800 bg-zinc-900/60 px-3 py-2.5"
      style={rule.isActive ? {} : { opacity: 0.55 }}
    >
      <span
        className="rounded px-1.5 py-0.5 font-mono text-[10px] font-bold uppercase"
        style={{
          color,
          background: `${color}22`,
          border: `1px solid ${color}55`,
        }}
      >
        {SEVERITY_LABEL[rule.severity]}
      </span>
      <div className="flex min-w-0 flex-1 flex-col">
        <span className="truncate font-mono text-xs text-zinc-200">{rule.name}</span>
        <span className="truncate text-[10px] text-zinc-500">{rule.description}</span>
      </div>
      <span className="font-mono text-[10px] text-zinc-500">{rule.cwe ?? "—"}</span>
      <Badge
        variant="outline"
        className="border-cyan-500/30 bg-cyan-500/5 font-mono text-[10px] text-cyan-400"
      >
        {rule.language}
      </Badge>
      {rule.hitsCount > 0 && (
        <Badge
          variant="outline"
          className="border-amber-500/30 bg-amber-500/5 font-mono text-[10px] text-amber-400"
        >
          {rule.hitsCount} hits
        </Badge>
      )}
      <div className="flex items-center gap-1.5">
        <span
          className={`font-mono text-[10px] font-bold uppercase ${rule.isActive ? "text-emerald-400" : "text-zinc-500"}`}
        >
          {rule.isActive ? "Active" : "Disabled"}
        </span>
        <Switch
          checked={rule.isActive}
          onCheckedChange={handleToggle}
          disabled={toggling}
          aria-label={rule.isActive ? "Deactivate rule" : "Activate rule"}
        />
        <Power
          className={`size-3.5 ${rule.isActive ? "text-emerald-400" : "text-zinc-600"}`}
        />
      </div>
    </motion.div>
  );
}

export default AdversarialAI;
