#!/bin/bash
# GuardianX one-command startup script for Windows (Git Bash)
# Starts: web app (3000) + sentinel engine (3003) + vuln target (3007)
# Auto-creates .env.local if missing (so scans actually work)
# Usage: bash start.sh  OR  double-click GuardianX-Desktop.bat

set -e

# ── Auto-detect project directory ──────────────────────────────────────────
# Works whether run from /d/GuardianX or from a cloned path
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"

LOG_DIR="$PROJECT_DIR/logs"
mkdir -p "$LOG_DIR"

echo "============================================"
echo "  GuardianX — Starting all services"
echo "============================================"
echo ""

# ── Step 0: Ensure .env.local exists ───────────────────────────────────────
# This file is gitignored so it gets lost on git pull. We recreate it
# automatically with the correct Supabase + SMTP credentials so the
# engine can connect to the database and scans actually work.
if [ ! -f "$PROJECT_DIR/.env.local" ]; then
  echo "[0/4] Creating .env.local (was missing — this is why scans fail!)"
  cat > "$PROJECT_DIR/.env.local" << 'ENVEOF'
# GuardianX Environment — auto-generated by start.sh
# Do NOT commit this file to git (it's in .gitignore)

# Supabase
NEXT_PUBLIC_SUPABASE_URL=https://ekjsieovspkuqdjhxwct.supabase.co
SUPABASE_URL=https://ekjsieovspkuqdjhxwct.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVranNpZW92c3BrdXFkamh4d2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0NzQ1MzQsImV4cCI6MjEwMTA1MDUzNH0.HIOLh6sUga-NgyegBtTYiFC8oYu8AMky3on5X9ULuKo
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVranNpZW92c3BrdXFkamh4d2N0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTQ3NDUzNCwiZXhwIjoyMTAxMDUwNTM0fQ.wSRwd24RFJHmQBlszGuVkGUmyA1dUzvEVM-ZMZJFIBA

# Security
JWT_SECRET=5fd8918bde57ff29249e8d90052006f80b75f1a32e6eeee5b51d9572d757da8f
BREAK_GLASS_KEY=399c2b4c63b8d41d26803569959580913ee97296835b7408098ddf2246a9d4b4

# SMTP (Hostinger)
SMTP_HOST=smtp.hostinger.com
SMTP_PORT=465
SMTP_USER=hello@guardianx.in
SMTP_PASS=Arhamalidar@05
SMTP_FROM="GuardianX <hello@guardianx.in>"

# Engine
ENGINE_URL=http://localhost:3003
ENVEOF
  echo "   ✓ .env.local created with Supabase + SMTP credentials"
  echo ""
else
  echo "[0/4] .env.local exists ✓"
fi

# Kill any existing processes on our ports
echo "[1/4] Cleaning up old processes..."
pkill -f "next dev" 2>/dev/null || true
pkill -f "bun.*index.ts" 2>/dev/null || true
sleep 2

# Start sentinel engine (with env vars loaded)
echo "[2/4] Starting Sentinel Engine (port 3003)..."
cd "$PROJECT_DIR/mini-services/sentinel-engine"
export $(grep -v '^#' "$PROJECT_DIR/.env.local" | grep -v '^$' | xargs -d '\n' 2>/dev/null || grep -v '^#' "$PROJECT_DIR/.env.local" | grep -v '^$' | env_import 2>/dev/null || true)
# Source the env file directly (works in Git Bash)
set -a
source "$PROJECT_DIR/.env.local" 2>/dev/null || true
set +a
bun run dev > "$LOG_DIR/engine.log" 2>&1 &
ENGINE_PID=$!
echo "   Engine PID: $ENGINE_PID (logs: logs/engine.log)"

# Start vuln-target (test app)
echo "[3/4] Starting VulnShop test target (port 3007)..."
cd "$PROJECT_DIR/mini-services/vuln-target"
bun run dev > "$LOG_DIR/vuln-target.log" 2>&1 &
VULN_PID=$!
echo "   VulnTarget PID: $VULN_PID (logs: logs/vuln-target.log)"

# Wait for engine to be ready
echo "   Waiting for engine to start..."
sleep 5

# Start web app
echo "[4/4] Starting Web App (port 3000)..."
cd "$PROJECT_DIR"
bun run dev > "$LOG_DIR/web.log" 2>&1 &
WEB_PID=$!
echo "   Web App PID: $WEB_PID (logs: logs/web.log)"

echo ""
echo "============================================"
echo "  All services started!"
echo "============================================"
echo ""
echo "  Web App:        http://localhost:3000"
echo "  Sentinel Engine: http://localhost:3003"
echo "  VulnShop:        http://localhost:3007"
echo ""
echo "  Logs in: $LOG_DIR/"
echo ""
echo "  Press Ctrl+C to stop all services"
echo ""

# Trap Ctrl+C to kill all background processes
trap "echo ''; echo 'Stopping all services...'; kill $ENGINE_PID $VULN_PID $WEB_PID 2>/dev/null; exit 0" INT TERM

# Keep the script running
wait
