// GET /api/self-attack/runs
//
// Returns the history of adversarial self-attack runs (last 20) with their
// miss rates + the rules added in each run. Used by the AdversarialAI
// component to render the runs history table.
//
// Each run was audit-logged at /api/self-attack (POST) with
// action="self-attack.run" and a JSON details payload. We walk those log
// entries, decode the JSON, and project a clean shape to the client.
//
// Auth-required (Bearer JWT).

import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { requireAuth } from "@/lib/auth";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

type Severity = "critical" | "high" | "medium" | "low";

interface RunRuleSummary {
  id?: string;
  name: string;
  severity: Severity;
  cwe: string | null;
  language: string;
}

interface SelfAttackRun {
  id: string;
  createdAt: string;
  actor: string;
  testedCount: number;
  missedCount: number;
  missRate: number;
  rulesAddedCount: number;
  rulesAdded: RunRuleSummary[];
  report: string;
}

// Also returns the current list of auto-generated DetectionRule rows so the
// client can render the Activate/Deactivate toggle list. These come from
// db.detectionRule (autoGenerated=true), sorted by createdAt desc.

interface DetectionRuleRow {
  id: string;
  name: string;
  description: string;
  pattern: string;
  severity: Severity;
  cwe: string | null;
  language: string;
  autoGenerated: boolean;
  isActive: boolean;
  hitsCount: number;
  createdAt: string;
}

interface RunsResponse {
  runs: SelfAttackRun[];
  rules: DetectionRuleRow[];
  totals: {
    totalRuns: number;
    totalTested: number;
    totalMissed: number;
    totalRulesAdded: number;
    avgMissRate: number;
    autoRulesActive: number;
    autoRulesTotal: number;
  };
}

function decodeRun(logRow: {
  id: string;
  createdAt: Date;
  actor: string;
  details: string | null;
}): SelfAttackRun | null {
  if (!logRow.details) return null;
  try {
    const parsed = JSON.parse(logRow.details) as {
      testedCount?: number;
      missedCount?: number;
      missRate?: number;
      rulesAddedCount?: number;
      rulesAdded?: RunRuleSummary[];
      report?: string;
    };
    return {
      id: logRow.id,
      createdAt: logRow.createdAt.toISOString(),
      actor: logRow.actor,
      testedCount: parsed.testedCount ?? 0,
      missedCount: parsed.missedCount ?? 0,
      missRate: parsed.missRate ?? 0,
      rulesAddedCount: parsed.rulesAddedCount ?? (parsed.rulesAdded?.length ?? 0),
      rulesAdded: Array.isArray(parsed.rulesAdded) ? parsed.rulesAdded : [],
      report: parsed.report ?? "",
    };
  } catch {
    return null;
  }
}

// PATCH /api/self-attack/runs
//
// Toggle isActive on an auto-generated DetectionRule. Used by the
// AdversarialAI component's "Activate/Deactivate" toggle next to each rule.
// Body: { ruleId: string, isActive: boolean }
// Returns the updated rule.
export async function PATCH(req: Request) {
  const auth = requireAuth(req);
  if (!auth.ok) return auth.response;

  let body: { ruleId?: string; isActive?: boolean };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }
  const ruleId = typeof body?.ruleId === "string" ? body.ruleId : "";
  const isActive = typeof body?.isActive === "boolean" ? body.isActive : true;
  if (!ruleId) {
    return NextResponse.json({ error: "ruleId required." }, { status: 400 });
  }

  try {
    const updated = await db.detectionRule.update({
      where: { id: ruleId },
      data: { isActive },
    });
    return NextResponse.json({
      id: updated.id,
      name: updated.name,
      isActive: updated.isActive,
      hitsCount: updated.hitsCount,
    });
  } catch (err) {
    console.error("[self-attack/runs PATCH] error:", err);
    return NextResponse.json(
      { error: "Failed to update rule. " + (err instanceof Error ? err.message : "Unknown error.") },
      { status: 500 },
    );
  }
}

export async function GET(req: Request) {
  const auth = requireAuth(req);
  if (!auth.ok) return auth.response;

  try {
    // Fetch the last 20 audit-log rows for self-attack runs + the full
    // list of auto-generated DetectionRules in parallel.
    const [auditRows, ruleRows] = await Promise.all([
      db.auditLog.findMany({
        where: { action: "self-attack.run" },
        orderBy: { createdAt: "desc" },
        take: 20,
      }),
      db.detectionRule.findMany({
        where: { autoGenerated: true },
        orderBy: { createdAt: "desc" },
      }),
    ]);

    const runs: SelfAttackRun[] = [];
    for (const r of auditRows) {
      const decoded = decodeRun({
        id: r.id,
        createdAt: r.createdAt,
        actor: r.actor,
        details: r.details,
      });
      if (decoded) runs.push(decoded);
    }

    const rules: DetectionRuleRow[] = ruleRows.map((r) => ({
      id: r.id,
      name: r.name,
      description: r.description,
      pattern: r.pattern,
      severity: r.severity as Severity,
      cwe: r.cwe,
      language: r.language,
      autoGenerated: r.autoGenerated,
      isActive: r.isActive,
      hitsCount: r.hitsCount,
      createdAt: r.createdAt.toISOString(),
    }));

    const totalTested = runs.reduce((sum, r) => sum + r.testedCount, 0);
    const totalMissed = runs.reduce((sum, r) => sum + r.missedCount, 0);
    const totalRulesAdded = runs.reduce((sum, r) => sum + r.rulesAddedCount, 0);
    const avgMissRate = totalTested > 0
      ? Math.round((totalMissed / totalTested) * 100)
      : 0;
    const autoRulesActive = rules.filter((r) => r.isActive).length;

    const response: RunsResponse = {
      runs,
      rules,
      totals: {
        totalRuns: runs.length,
        totalTested,
        totalMissed,
        totalRulesAdded,
        avgMissRate,
        autoRulesActive,
        autoRulesTotal: rules.length,
      },
    };
    return NextResponse.json(response);
  } catch (err) {
    console.error("[self-attack/runs] error:", err);
    return NextResponse.json(
      { error: "Failed to load run history. " + (err instanceof Error ? err.message : "Unknown error.") },
      { status: 500 },
    );
  }
}
