import { NextResponse } from "next/server";
import { createHmac } from "node:crypto";

export const dynamic = "force-dynamic";

// ── Zero-Knowledge Security Proofs — verification endpoint ──────────────
//
// POST /api/zk-proof/verify — PUBLIC (no auth required). Anyone holding
// a proof JSON generated by /api/zk-proof/generate can verify it here.
//
// Body: { proof: { claim, threshold, dataHash, nonce, signature, generatedAt, version } }
//
// Returns:
//   { valid: true,  claim, threshold, generatedAt }
//   { valid: false, reason: "missing_fields" | "bad_signature" | "unsupported_version" }
//
// The verifier recomputes HMAC-SHA256(JWT_SECRET, claim|threshold|dataHash|nonce|generatedAt)
// and compares in constant time. If the secret has rotated since the
// proof was generated, verification will fail (the proof holder must
// regenerate the proof with the new signing key).

const JWT_SECRET = process.env.JWT_SECRET || "dev-only-secret-not-for-production-use";

interface ProofPayload {
  claim?: unknown;
  threshold?: unknown;
  dataHash?: unknown;
  nonce?: unknown;
  signature?: unknown;
  generatedAt?: unknown;
  version?: unknown;
  actualScore?: unknown;
  meetsThreshold?: unknown;
}

function isString(v: unknown): v is string {
  return typeof v === "string" && v.length > 0;
}

export async function POST(req: Request) {
  let body: Record<string, unknown> = {};
  try {
    body = (await req.json()) as Record<string, unknown>;
  } catch {
    return NextResponse.json(
      { valid: false, reason: "invalid_json_body" },
      { status: 400 }
    );
  }

  const proof = body.proof as ProofPayload | undefined;
  if (!proof || typeof proof !== "object") {
    return NextResponse.json(
      { valid: false, reason: "missing_proof" },
      { status: 400 }
    );
  }

  const { claim, threshold, dataHash, nonce, signature, generatedAt, version } = proof;

  if (!isString(claim) || !isString(dataHash) || !isString(nonce) || !isString(signature) || !isString(generatedAt)) {
    return NextResponse.json(
      { valid: false, reason: "missing_fields" },
      { status: 400 }
    );
  }
  if (typeof threshold !== "number" || !Number.isFinite(threshold)) {
    return NextResponse.json(
      { valid: false, reason: "missing_fields" },
      { status: 400 }
    );
  }
  if (version !== 1) {
    return NextResponse.json(
      { valid: false, reason: "unsupported_version" },
      { status: 400 }
    );
  }

  // Reject proofs older than 90 days — posture claims go stale.
  const generatedAtDate = new Date(generatedAt);
  if (isNaN(generatedAtDate.getTime())) {
    return NextResponse.json(
      { valid: false, reason: "invalid_timestamp" },
      { status: 400 }
    );
  }
  const ageMs = Date.now() - generatedAtDate.getTime();
  if (ageMs < 0 || ageMs > 90 * 24 * 60 * 60 * 1000) {
    return NextResponse.json(
      { valid: false, reason: "proof_expired_or_not_yet_valid" },
      { status: 400 }
    );
  }

  // Recompute the expected signature.
  const signedValue = `${claim}|${threshold}|${dataHash}|${nonce}|${generatedAt}`;
  const expected = createHmac("sha256", JWT_SECRET)
    .update(signedValue, "utf8")
    .digest("hex");

  // Constant-time comparison.
  const a = Buffer.from(expected, "utf8");
  const b = Buffer.from(signature, "utf8");
  let equal = a.length === b.length;
  if (equal) {
    for (let i = 0; i < a.length; i++) {
      if (a[i] !== b[i]) equal = false;
    }
  }

  if (!equal) {
    return NextResponse.json(
      { valid: false, reason: "bad_signature" },
      { status: 200 } // 200 (not 401) so verifiers don't conflate "invalid" with "transport error"
    );
  }

  return NextResponse.json({
    valid: true,
    claim,
    threshold,
    generatedAt,
    version: 1,
    issuer: "GuardianX",
  });
}
