// POST /api/self-attack
//
// Adversarial AI Self-Attack — an AI agent whose job is to find blind spots
// in GuardianX's own detection. It generates synthetic vulnerable code
// snippets that *should* be flagged, runs them through the existing scan
// logic (regex-based), and if GuardianX misses any, the AI auto-writes a
// new detection rule + saves it to the DetectionRule table.
//
// Flow:
//   1. Pick a deterministic-but-rotating subset of 5-10 snippets from the
//      hardcoded 24-pattern vuln library (SQLi, XSS, SSRF, path traversal,
//      command injection, deserialization, hardcoded secrets, weak crypto,
//      prototype pollution, ReDoS, XXE, open redirect, timing attacks, JWT
//      'none' alg, etc.).
//   2. For each snippet, run the EXISTING scan logic (a small set of regex
//      patterns that intentionally has gaps). If the snippet wasn't flagged
//      → it's a false negative (a miss).
//   3. For each miss, ask the LLM (via chatWithFallback) to write a new
//      detection rule: name, description, regex pattern, severity, CWE.
//      On LLM failure, derive a heuristic regex from the vuln pattern.
//   4. Save each new rule to db.detectionRule with autoGenerated=true.
//   5. Audit-log the run (action="self-attack.run") so /api/self-attack/runs
//      can render history.
//   6. Return { testedCount, missedCount, rulesAdded, report }.
//
// Auth-required (Bearer JWT). Dark red theme on the client.

import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { requireAuth } from "@/lib/auth";
import { chatWithFallback } from "@/lib/llm";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

// ── Types ────────────────────────────────────────────────────────────────
type Severity = "critical" | "high" | "medium" | "low";

interface VulnPattern {
  id: string;
  name: string;
  cwe: string;
  severity: Severity;
  language: string;
  code: string;
  expectedDetection: string; // what a "good" scanner should flag
}

interface ExistingDetection {
  name: string;
  pattern: RegExp;
  severity: Severity;
  cwe: string;
}

interface ScanHit {
  ruleName: string;
  severity: Severity;
  cwe: string;
  snippet: string;
}

interface RuleAdded {
  id: string;
  name: string;
  severity: Severity;
  cwe: string | null;
  language: string;
}

interface SelfAttackResult {
  testedCount: number;
  missedCount: number;
  rulesAdded: RuleAdded[];
  report: string;
  runs: Array<{
    vulnId: string;
    vulnName: string;
    severity: Severity;
    cwe: string;
    language: string;
    detected: boolean;
    matchedRule?: string;
    snippet: string;
  }>;
  generatedAt: string;
}

// ── Vuln library — 24 patterns spanning 14 vulnerability classes ──────────
// Each snippet is real, exploitable code that SHOULD trigger a finding.
// Some of these are caught by the existing scan logic; others represent
// blind spots the adversarial AI is supposed to discover.
const VULN_LIBRARY: VulnPattern[] = [
  // ── Caught by existing logic (positive coverage) ───────────────────────
  {
    id: "eval-user-input",
    name: "eval() on user input",
    cwe: "CWE-95",
    severity: "critical",
    language: "javascript",
    code: "function calc(req) {\n  return eval(req.body.expression);\n}",
    expectedDetection: "eval() called with user-controlled input",
  },
  {
    id: "innerhtml-assignment",
    name: "innerHTML assignment from user input",
    cwe: "CWE-79",
    severity: "high",
    language: "javascript",
    code: "function renderProfile(name) {\n  document.getElementById('profile').innerHTML = name;\n}",
    expectedDetection: "innerHTML assigned from untrusted source",
  },
  {
    id: "document-write-xss",
    name: "document.write XSS",
    cwe: "CWE-79",
    severity: "high",
    language: "javascript",
    code: "app.get('/hello', (req, res) => {\n  res.send('<script>document.write(' + req.query.name + ')</script>');\n});",
    expectedDetection: "document.write with user input",
  },
  {
    id: "sqli-string-concat",
    name: "SQL injection via string concatenation",
    cwe: "CWE-89",
    severity: "critical",
    language: "javascript",
    code: "function getUser(id) {\n  return db.query('SELECT * FROM users WHERE id = ' + id);\n}",
    expectedDetection: "SQL query built via string concatenation with input",
  },
  {
    id: "child-process-exec",
    name: "Command injection via child_process.exec",
    cwe: "CWE-78",
    severity: "critical",
    language: "javascript",
    code: "const { exec } = require('child_process');\nfunction runTask(req) {\n  exec('ping ' + req.body.host);\n}",
    expectedDetection: "child_process.exec with user input",
  },
  {
    id: "md5-hash",
    name: "Weak crypto (MD5)",
    cwe: "CWE-327",
    severity: "medium",
    language: "javascript",
    code: "function hashPassword(pw) {\n  return crypto.createHash('md5').update(pw).digest('hex');\n}",
    expectedDetection: "MD5 used for hashing",
  },
  {
    id: "hardcoded-password",
    name: "Hardcoded password",
    cwe: "CWE-798",
    severity: "high",
    language: "javascript",
    code: "const config = {\n  password: 'admin123',\n  host: 'prod-db.local'\n};",
    expectedDetection: "Hardcoded credential 'password' literal",
  },
  {
    id: "insecure-http",
    name: "Insecure HTTP request",
    cwe: "CWE-319",
    severity: "medium",
    language: "javascript",
    code: "async function fetchConfig() {\n  const res = await fetch('http://api.internal/config');\n  return res.json();\n}",
    expectedDetection: "HTTP (no TLS) request",
  },
  {
    id: "path-traversal-readfile",
    name: "Path traversal via fs.readFile",
    cwe: "CWE-22",
    severity: "high",
    language: "javascript",
    code: "const fs = require('fs');\napp.get('/file', (req, res) => {\n  const content = fs.readFileSync(req.query.path);\n  res.send(content);\n});",
    expectedDetection: "fs.readFile with user input (path traversal)",
  },
  {
    id: "eval-settimeout",
    name: "Indirect eval via setTimeout(string)",
    cwe: "CWE-95",
    severity: "high",
    language: "javascript",
    code: "function defer(payload) {\n  setTimeout(payload, 100);\n}",
    expectedDetection: "setTimeout called with string (indirect eval)",
  },

  // ── MISSED by existing logic (these are the blind spots) ──────────────
  {
    id: "ssrf-fetch-url",
    name: "SSRF via fetch(userUrl)",
    cwe: "CWE-918",
    severity: "critical",
    language: "javascript",
    code: "async function proxy(req) {\n  const url = req.body.url;\n  const r = await fetch(url);\n  return r.text();\n}",
    expectedDetection: "fetch() called with user-controlled URL (SSRF)",
  },
  {
    id: "path-traversal-join",
    name: "Path traversal via path.join",
    cwe: "CWE-22",
    severity: "high",
    language: "javascript",
    code: "const path = require('path');\napp.get('/download', (req, res) => {\n  const fp = path.join(__dirname, 'uploads', req.query.filename);\n  res.sendFile(fp);\n});",
    expectedDetection: "path.join with user input (path traversal)",
  },
  {
    id: "cmd-injection-spawn-shell",
    name: "Command injection via spawn(shell:true)",
    cwe: "CWE-78",
    severity: "critical",
    language: "javascript",
    code: "const { spawn } = require('child_process');\nfunction runCmd(input) {\n  spawn(input.cmd, input.args, { shell: true });\n}",
    expectedDetection: "spawn with shell:true and user input",
  },
  {
    id: "insecure-deserialize",
    name: "Insecure deserialization (node-serialize)",
    cwe: "CWE-502",
    severity: "critical",
    language: "javascript",
    code: "const serialize = require('node-serialize');\napp.post('/restore', (req, res) => {\n  const session = serialize.unserialize(req.body.session);\n  res.json(session);\n});",
    expectedDetection: "Insecure deserialize (node-serialize.unserialize)",
  },
  {
    id: "prototype-pollution-merge",
    name: "Prototype pollution via deep merge",
    cwe: "CWE-1321",
    severity: "high",
    language: "javascript",
    code: "function merge(target, src) {\n  for (const k in src) {\n    target[k] = (typeof src[k] === 'object') ? merge(target[k] || {}, src[k]) : src[k];\n  }\n  return target;\n}",
    expectedDetection: "Recursive object merge without __proto__ guard (prototype pollution)",
  },
  {
    id: "redos-user-regex",
    name: "ReDoS via user-controlled regex",
    cwe: "CWE-1333",
    severity: "high",
    language: "javascript",
    code: "function validate(input, pattern) {\n  const re = new RegExp(pattern);\n  return re.test(input);\n}",
    expectedDetection: "new RegExp() with user input (ReDoS)",
  },
  {
    id: "open-redirect",
    name: "Open redirect via res.redirect(userInput)",
    cwe: "CWE-601",
    severity: "medium",
    language: "javascript",
    code: "app.get('/login', (req, res) => {\n  if (req.query.next) return res.redirect(req.query.next);\n  res.render('login');\n});",
    expectedDetection: "res.redirect with user input (open redirect)",
  },
  {
    id: "jwt-none-alg",
    name: "JWT 'none' algorithm accepted",
    cwe: "CWE-345",
    severity: "critical",
    language: "javascript",
    code: "const jwt = require('jsonwebtoken');\nfunction verify(token) {\n  return jwt.verify(token, '', { algorithms: ['none', 'HS256'] });\n}",
    expectedDetection: "JWT verify with 'none' algorithm allowed",
  },
  {
    id: "timing-attack-compare",
    name: "Timing attack: non-constant-time comparison",
    cwe: "CWE-208",
    severity: "medium",
    language: "javascript",
    code: "function checkToken(userToken, storedToken) {\n  return userToken === storedToken;\n}",
    expectedDetection: "Token comparison with === (timing attack)",
  },
  {
    id: "hardcoded-api-key",
    name: "Hardcoded API key",
    cwe: "CWE-798",
    severity: "high",
    language: "javascript",
    code: "const STRIPE_SECRET = 'sk_live_FAKE_KEY_FOR_TESTING_ONLY';\nconst stripe = require('stripe')(STRIPE_SECRET);",
    expectedDetection: "Hardcoded API key (sk_live_ prefix)",
  },
  {
    id: "weak-rng",
    name: "Weak RNG for security-critical value",
    cwe: "CWE-338",
    severity: "high",
    language: "javascript",
    code: "function genResetToken() {\n  return Math.random().toString(36).slice(2);\n}",
    expectedDetection: "Math.random() used for security token",
  },
  {
    id: "xxe-libxml",
    name: "XXE via XML parser with default options",
    cwe: "CWE-611",
    severity: "high",
    language: "javascript",
    code: "const libxmljs = require('libxmljs');\nfunction parse(xml) {\n  return libxmljs.parseXml(xml);\n}",
    expectedDetection: "XML parser without disabling external entities (XXE)",
  },
  {
    id: "python-pickle-deserialize",
    name: "Python pickle insecure deserialization",
    cwe: "CWE-502",
    severity: "critical",
    language: "python",
    code: "import pickle\n\ndef restore(req):\n    return pickle.loads(req.body)",
    expectedDetection: "pickle.loads with user input (RCE)",
  },
  {
    id: "python-eval",
    name: "Python eval() on user input",
    cwe: "CWE-95",
    severity: "critical",
    language: "python",
    code: "def calculate(req):\n    return eval(req.body['expression'])",
    expectedDetection: "Python eval() with user input",
  },
];

// ── Existing scan logic — INTENTIONALLY has gaps ─────────────────────────
// This represents GuardianX's *current* detection capability. The adversarial
// AI's job is to find vulns that AREN'T caught here and write new rules.
const EXISTING_DETECTIONS: ExistingDetection[] = [
  { name: "eval()", pattern: /\beval\s*\(/, severity: "critical", cwe: "CWE-95" },
  { name: "innerHTML assignment", pattern: /\.innerHTML\s*=/, severity: "high", cwe: "CWE-79" },
  { name: "document.write", pattern: /document\.write\s*\(/, severity: "high", cwe: "CWE-79" },
  { name: "SQL string concat", pattern: /(?:SELECT|INSERT|UPDATE|DELETE)\b[^;]*\+\s*\w/i, severity: "critical", cwe: "CWE-89" },
  { name: "child_process.exec", pattern: /(?:child_process|require\(['"]child_process['"]\))[\s\S]*?\.exec\s*\(/, severity: "critical", cwe: "CWE-78" },
  { name: "MD5 hash", pattern: /createHash\(['"]md5['"]\)/, severity: "medium", cwe: "CWE-327" },
  { name: "Hardcoded password", pattern: /\bpassword\s*[:=]\s*['"][^'"]+['"]/, severity: "high", cwe: "CWE-798" },
  { name: "Insecure HTTP", pattern: /fetch\(\s*['"]http:\/\//, severity: "medium", cwe: "CWE-319" },
  { name: "Path traversal fs.readFile", pattern: /fs\.read\w*\s*\(\s*req\./, severity: "high", cwe: "CWE-22" },
  { name: "Python pickle.loads", pattern: /pickle\.loads\s*\(/, severity: "critical", cwe: "CWE-502" },
  { name: "Python eval()", pattern: /\beval\s*\(\s*req\./, severity: "critical", cwe: "CWE-95" },
  { name: "setTimeout string", pattern: /setTimeout\s*\(\s*['"][^'"]+['"]/, severity: "high", cwe: "CWE-95" },
];

function scanWithExistingLogic(code: string): ScanHit[] {
  const hits: ScanHit[] = [];
  for (const det of EXISTING_DETECTIONS) {
    const m = det.pattern.exec(code);
    if (m) {
      const start = Math.max(0, (m.index ?? 0) - 20);
      const end = Math.min(code.length, (m.index ?? 0) + 80);
      hits.push({
        ruleName: det.name,
        severity: det.severity,
        cwe: det.cwe,
        snippet: code.slice(start, end).replace(/\s+/g, " ").trim(),
      });
    }
  }
  return hits;
}

// ── JSON extraction (mirrors src/lib/sentinel/engine/ai.ts) ────────────────
function extractJson(raw: string): string {
  let s = raw.trim();
  const fence = s.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fence) s = fence[1].trim();
  const first = s.search(/[[{]/);
  const lastBrace = s.lastIndexOf("}");
  const lastBracket = s.lastIndexOf("]");
  const last = Math.max(lastBrace, lastBracket);
  if (first !== -1 && last !== -1 && last > first) {
    s = s.slice(first, last + 1);
  }
  return s.trim();
}

// ── Heuristic rule derivation (fallback when LLM is unavailable) ──────────
// Derives a regex from the vuln pattern by extracting the most
// security-relevant token from the code snippet.
function heuristicRuleForVuln(v: VulnPattern): {
  name: string;
  description: string;
  pattern: string;
  severity: Severity;
  cwe: string;
  language: string;
} {
  let pattern = "";
  switch (v.id) {
    case "ssrf-fetch-url":
      pattern = String.raw`fetch\s*\(\s*(?:req|request|input|user|payload)\.`;
      break;
    case "path-traversal-join":
      pattern = String.raw`path\.join\s*\([\s\S]*?req\.`;
      break;
    case "cmd-injection-spawn-shell":
      pattern = String.raw`spawn\s*\([^)]*shell\s*:\s*true`;
      break;
    case "insecure-deserialize":
      pattern = String.raw`serialize\.unserialize\s*\(`;
      break;
    case "prototype-pollution-merge":
      pattern = String.raw`function\s+merge\s*\(\s*\w+\s*,\s*\w+\s*\)[\s\S]*?for\s*\(\s*(?:const|let|var)?\s*\w+\s+in\b`;
      break;
    case "redos-user-regex":
      pattern = String.raw`new\s+RegExp\s*\(`;
      break;
    case "open-redirect":
      pattern = String.raw`res\.redirect\s*\(\s*req\.`;
      break;
    case "jwt-none-alg":
      pattern = String.raw`algorithms\s*:\s*\[[^\]]*['"]none['"]`;
      break;
    case "timing-attack-compare":
      pattern = String.raw`(?:token|secret|password|key|hash)\w*\s*===\s*(?:token|secret|password|key|stored)`;
      break;
    case "hardcoded-api-key":
      pattern = String.raw`['"]sk_(?:live|test)_\w{20,}['"]`;
      break;
    case "weak-rng":
      pattern = String.raw`Math\.random\s*\(\s*\)[\s\S]{0,80}(?:token|secret|password|key|nonce|otp)`;
      break;
    case "xxe-libxml":
      pattern = String.raw`libxmljs\.parseXml\s*\(`;
      break;
    default: {
      // Generic: take the most distinctive function call from the code.
      const fnMatch = v.code.match(/(\w+(?:\.\w+)*)\s*\(/);
      const fn = fnMatch?.[1] ?? "vulnerable";
      pattern = String.raw`${fn}\s*\(`;
    }
  }
  return {
    name: `Auto: ${v.name}`,
    description: `Heuristic rule auto-generated for ${v.name} (${v.cwe}). ${v.expectedDetection}.`,
    pattern,
    severity: v.severity,
    cwe: v.cwe,
    language: v.language,
  };
}

// ── LLM-backed rule generation ────────────────────────────────────────────
async function llmGenerateRule(v: VulnPattern): Promise<{
  name: string;
  description: string;
  pattern: string;
  severity: Severity;
  cwe: string;
  language: string;
} | null> {
  const system = [
    "You are GuardianX's Adversarial AI — a self-attacking red team whose job is to find blind spots in GuardianX's own detection.",
    "You will be given a vulnerable code snippet that the existing scanner MISSED.",
    "Your job: produce a regex-based detection rule that would catch this class of vulnerability in future scans.",
    "Return STRICT JSON only — no prose, no markdown fences.",
  ].join(" ");

  const user = [
    `Vulnerability: ${v.name}`,
    `CWE: ${v.cwe}`,
    `Severity: ${v.severity}`,
    `Language: ${v.language}`,
    `Code:`,
    "```" + v.language,
    v.code,
    "```",
    "",
    "Write a regex pattern that would match this kind of vulnerable code (escape backslashes for JSON).",
    "Return JSON in this EXACT shape:",
    '{"name":"<short name>","description":"<1-2 sentences>","pattern":"<regex string>","severity":"critical|high|medium|low","cwe":"<CWE-NNN>","language":"<lang>"}',
    "Rules:",
    "- The regex MUST be a valid JavaScript regex pattern (the part between /.../), without surrounding slashes or flags.",
    "- The regex MUST match the dangerous construct, not just the literal snippet — generalize to catch variants.",
    "- No markdown fences. No prose. Just JSON.",
  ].join("\n");

  const result = await chatWithFallback({
    system,
    messages: [{ role: "user", content: user }],
    fallback: () => "", // empty = caller falls back to heuristic
    temperature: 0.4,
    maxTokens: 600,
  });

  if (!result.content || result.content.trim() === "") return null;

  let parsed: {
    name?: string;
    description?: string;
    pattern?: string;
    severity?: string;
    cwe?: string;
    language?: string;
  } = {};
  try {
    parsed = JSON.parse(extractJson(result.content)) as typeof parsed;
  } catch {
    return null;
  }

  if (!parsed.pattern || !parsed.name) return null;

  // Validate that the regex actually compiles + matches the snippet.
  let compiled: RegExp;
  try {
    compiled = new RegExp(parsed.pattern);
  } catch {
    return null;
  }
  if (!compiled.test(v.code)) return null;

  const sev = (["critical", "high", "medium", "low"].includes(parsed.severity ?? "")
    ? parsed.severity
    : v.severity) as Severity;

  return {
    name: String(parsed.name).slice(0, 120),
    description: String(parsed.description ?? "").slice(0, 600),
    pattern: String(parsed.pattern),
    severity: sev,
    cwe: parsed.cwe ?? v.cwe,
    language: parsed.language ?? v.language,
  };
}

// ── Route handler ──────────────────────────────────────────────────────────
export async function POST(req: Request) {
  const auth = requireAuth(req);
  if (!auth.ok) return auth.response;

  try {
    // Pick a rotating subset of 5-10 vulns from the library. The rotation
    // changes every hour so re-runs surface different blind spots over time.
    const hourBucket = Math.floor(Date.now() / (1000 * 60 * 60));
    const targetCount = 7 + (hourBucket % 4); // 7..10 snippets
    const rotated = [...VULN_LIBRARY];
    // Deterministic rotation: shift by hourBucket so the order changes.
    const shift = hourBucket % rotated.length;
    const subset = [
      ...rotated.slice(shift),
      ...rotated.slice(0, shift),
    ].slice(0, Math.min(targetCount, VULN_LIBRARY.length));

    const runRows: SelfAttackResult["runs"] = [];
    const rulesAdded: RuleAdded[] = [];
    let missedCount = 0;

    for (const vuln of subset) {
      const hits = scanWithExistingLogic(vuln.code);
      // A "miss" = no existing detection fired on this snippet (or the
      // detection's CWE didn't match the vuln's CWE — i.e. wrong-class hit).
      const matchedByCwe = hits.some((h) => h.cwe === vuln.cwe);
      const detected = hits.length > 0 && matchedByCwe;
      if (!detected) missedCount++;

      runRows.push({
        vulnId: vuln.id,
        vulnName: vuln.name,
        severity: vuln.severity,
        cwe: vuln.cwe,
        language: vuln.language,
        detected,
        matchedRule: detected ? hits[0]?.ruleName : undefined,
        snippet: vuln.code.split("\n")[0]?.slice(0, 80) ?? "",
      });

      // For misses, generate + persist a new detection rule.
      if (!detected) {
        // First check if we already have a rule for this vuln (idempotent
        // — don't double-add). Match by name suffix or CWE+language.
        const existing = await db.detectionRule.findFirst({
          where: {
            OR: [
              { name: { contains: vuln.name } },
              { cwe: vuln.cwe, language: vuln.language },
            ],
          },
        });
        if (existing) {
          // Already have a rule for this blind spot; skip (don't duplicate).
          continue;
        }

        // Try LLM, fall back to heuristic.
        let rule = await llmGenerateRule(vuln).catch(() => null);
        if (!rule) {
          rule = heuristicRuleForVuln(vuln);
        }

        const saved = await db.detectionRule.create({
          data: {
            name: rule.name,
            description: rule.description,
            pattern: rule.pattern,
            severity: rule.severity,
            cwe: rule.cwe,
            language: rule.language,
            autoGenerated: true,
            createdBy: auth.user.email,
            isActive: true,
            hitsCount: 0,
          },
        });
        rulesAdded.push({
          id: saved.id,
          name: saved.name,
          severity: saved.severity as Severity,
          cwe: saved.cwe,
          language: saved.language,
        });
      }
    }

    const testedCount = subset.length;
    const missRate = testedCount > 0 ? Math.round((missedCount / testedCount) * 100) : 0;

    const report = [
      `Adversarial self-attack completed at ${new Date().toISOString()}.`,
      `Tested ${testedCount} synthetic vulnerable snippets against GuardianX's existing scan logic.`,
      `${missedCount} of ${testedCount} (${missRate}%) were NOT detected — these represent blind spots.`,
      `Auto-wrote ${rulesAdded.length} new detection rule(s) to the DetectionRule table.`,
      rulesAdded.length > 0
        ? `New rules: ${rulesAdded.map((r) => `${r.name} (${r.severity}, ${r.cwe ?? "n/a"})`).join("; ")}`
        : `No new rules added (all blind spots already had rules).`,
    ].join(" ");

    // Audit-log the run so /api/self-attack/runs can render history.
    try {
      await db.auditLog.create({
        data: {
          action: "self-attack.run",
          entity: "DetectionRule",
          actor: auth.user.email,
          details: JSON.stringify({
            testedCount,
            missedCount,
            missRate,
            rulesAddedCount: rulesAdded.length,
            rulesAdded: rulesAdded.map(({ id, name, severity, cwe, language }) => ({
              id, name, severity, cwe, language,
            })),
            runRows,
            report,
            generatedAt: new Date().toISOString(),
          }),
        },
      });
    } catch (auditErr) {
      // Audit log failure is non-fatal — the run still succeeded.
      console.warn("[self-attack] audit-log write failed:", auditErr instanceof Error ? auditErr.message : auditErr);
    }

    const result: SelfAttackResult = {
      testedCount,
      missedCount,
      rulesAdded,
      report,
      runs: runRows,
      generatedAt: new Date().toISOString(),
    };
    return NextResponse.json(result);
  } catch (err) {
    console.error("[self-attack] error:", err);
    return NextResponse.json(
      { error: "Self-attack failed. " + (err instanceof Error ? err.message : "Unknown error.") },
      { status: 500 },
    );
  }
}

// GET — convenience for clients that want to fetch the latest run summary
// without walking the runs history. Returns the same shape as POST.
export async function GET(req: Request) {
  const auth = requireAuth(req);
  if (!auth.ok) return auth.response;

  try {
    const last = await db.auditLog.findFirst({
      where: { action: "self-attack.run" },
      orderBy: { createdAt: "desc" },
    });
    if (!last || !last.details) {
      return NextResponse.json({
        testedCount: 0,
        missedCount: 0,
        rulesAdded: [],
        report: "No self-attack runs yet. Click RUN SELF-ATTACK to begin.",
        runs: [],
        generatedAt: new Date().toISOString(),
      });
    }
    try {
      const parsed = JSON.parse(last.details) as SelfAttackResult;
      return NextResponse.json(parsed);
    } catch {
      return NextResponse.json({
        testedCount: 0,
        missedCount: 0,
        rulesAdded: [],
        report: "Last run log was corrupt.",
        runs: [],
        generatedAt: last.createdAt.toISOString(),
      });
    }
  } catch (err) {
    console.error("[self-attack GET] error:", err);
    return NextResponse.json(
      { error: "Failed to load last run." + (err instanceof Error ? err.message : "") },
      { status: 500 },
    );
  }
}
