import {
  Bug,
  Crosshair,
  Swords,
  ScanLine,
  FileText,
  KeyRound,
  Gauge,
  Globe,
  Wand2,
  Heart,
  Link2,
  Gavel,
  Lock,
  Skull,
  Activity,
  Radar,
  Network,
  GitBranch,
  AlertTriangle,
  Workflow,
  Eye,
  Webhook,
  Brain,
  Rocket,
  FlaskConical,
  Shield,
  FileCode2,
  ShieldCheck,
  Mic,
  Hand,
  Cpu,
  Database,
  Bot,
  Sparkles,
  Drama,
  Bird,
  Users,
  Orbit,
  Clapperboard,
  TrendingUp,
  Shuffle,
  Coins,
  Terminal,
  Atom,
  Rewind,
  Glasses,
  EyeOff,
  Siren,
  Telescope,
  SlidersHorizontal,
  CreditCard,
  Settings,
  UserCog,
  PenLine,
  Trophy,
  LineChart,
  GitMerge,
  Briefcase,
  FolderGit2,
  type LucideIcon,
} from "lucide-react";

export interface Feature {
  icon: LucideIcon;
  title: string;
  category: string;
  desc: string;
  color: string;
  neon: string;
  border: string;
  glow: string;
  bg: string;
  isNew?: boolean;
}

export const FEATURES: Feature[] = [
  {
    icon: Bug,
    title: "AI Vulnerability Detection",
    category: "SAST",
    desc: "AI reads your source code and identifies real, exploitable vulnerabilities with CVE/CWE mapping, confidence scores, and the exact vulnerable snippet.",
    color: "text-red-400",
    neon: "neon-red",
    border: "border-red-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(239,68,68,0.2)]",
    bg: "bg-red-500/5",
  },
  {
    icon: Crosshair,
    title: "PoC Exploit Playground",
    category: "Exploit",
    desc: "For every vulnerability, the AI generates a working proof-of-concept exploit. Run it against the original code to prove the vuln is real, then against the patched code to prove the fix works.",
    color: "text-orange-400",
    neon: "neon-orange",
    border: "border-orange-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(249,115,22,0.2)]",
    bg: "bg-orange-500/5",
  },
  {
    icon: Swords,
    title: "Adversarial Red-Team Arena",
    category: "Self-Attack",
    desc: "After patching, a second AI persona attacks its own fix. If it finds a bypass, the defender iterates. Loop until the attacker concedes, the patch is battle-tested before human review.",
    color: "text-amber-400",
    neon: "neon-amber",
    border: "border-amber-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(245,158,11,0.2)]",
    bg: "bg-amber-500/5",
  },
  {
    icon: Crosshair,
    title: "RedAgent VAPT Engine",
    category: "DAST",
    desc: "Autonomous penetration testing against live targets. The AI crawls the app, plans category-appropriate attacks, fires real HTTP payloads, and confirms exploitation with full evidence.",
    color: "text-red-400",
    neon: "neon-red",
    border: "border-red-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(239,68,68,0.2)]",
    bg: "bg-red-500/5",
  },
  {
    icon: ScanLine,
    title: "Sensitive Data Exposure Scanner",
    category: "Secrets",
    desc: "Systematically detects exposed AWS/Stripe/GitHub keys, JWTs, private keys, passwords, SSNs, and credit cards. Probes 22+ known exposure paths. All samples redacted, proves the leak without exfiltrating.",
    color: "text-purple-400",
    neon: "neon-purple",
    border: "border-purple-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(168,85,247,0.2)]",
    bg: "bg-purple-500/5",
  },
  {
    icon: FileText,
    title: "Professional VAPT Reports",
    category: "Reporting",
    desc: "Generate a 15-page PDF VAPT report with front page, TOC, document control, executive summary, methodology, findings master table, detailed PoC evidence, compliance mapping, and cleanup certificate.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: KeyRound,
    title: "Encrypted Git Integration",
    category: "Credentials",
    desc: "Connect real private repos with AES-256-GCM encrypted credentials. Tokens are encrypted at rest, never shown again, never leaked in logs. Clone, explore, and import files for scanning.",
    color: "text-sky-400",
    neon: "neon-sky",
    border: "border-sky-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(14,165,233,0.2)]",
    bg: "bg-sky-500/5",
  },
  {
    icon: Gauge,
    title: "PostureScore",
    category: "Metrics",
    desc: "A 0–100 security credit score per codebase, computed from open vulns, sandbox pass rates, and adversarial win rates. Letter grades A–F. Trend over time. Exec-friendly at-a-glance posture.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: Globe,
    title: "Continuous Threat Intel",
    category: "Live Feed",
    desc: "Monitors live CVE disclosures via web search and cross-references them against your codebases. New 0-day for a lib you use? GuardianX flags it high-relevance before you've heard of it.",
    color: "text-cyan-400",
    neon: "neon-cyan",
    border: "border-cyan-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(6,182,212,0.2)]",
    bg: "bg-cyan-500/5",
  },
  {
    icon: Wand2,
    title: "AI Remediation Copilot",
    category: "Copilot",
    desc: "Inside every patch: ask the AI to explain the fix, generate an improved production-ready version, or produce a hardened defense-in-depth variant with input validation and rate limiting.",
    color: "text-violet-400",
    neon: "neon-violet",
    border: "border-violet-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(139,92,246,0.2)]",
    bg: "bg-violet-500/5",
  },
  {
    icon: Heart,
    title: "Self-Healing Runtime",
    category: "Runtime",
    desc: "Live runtime monitoring tracks which functions are vulnerable vs healed. One-click hot-swap deploys a patched function at runtime with zero downtime. Auto-heal when an attack is detected.",
    color: "text-rose-400",
    neon: "neon-rose",
    border: "border-rose-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(244,63,94,0.2)]",
    bg: "bg-rose-500/5",
  },
  {
    icon: Link2,
    title: "Cryptographic Patch Attestation",
    category: "Trust",
    desc: "Every approved patch is hash-chained into an immutable SHA-256 ledger. Tamper-evident: any modification to a past attestation breaks every subsequent hash. Enterprise-grade audit trail.",
    color: "text-teal-400",
    neon: "neon-teal",
    border: "border-teal-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(20,184,166,0.2)]",
    bg: "bg-teal-500/5",
  },
  {
    icon: Gavel,
    title: "DPDPA & Multi-Framework Compliance",
    category: "GRC",
    desc: "Map every finding to DPDPA 2023, GDPR, HIPAA, PCI-DSS, ISO 27001, and SOC 2. Track section-level compliance, generate audit reports, and auto-draft 72-hour breach notifications.",
    color: "text-purple-400",
    neon: "neon-purple",
    border: "border-purple-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(168,85,247,0.2)]",
    bg: "bg-purple-500/5",
  },
  {
    icon: Lock,
    title: "Data Privacy Scanner",
    category: "Privacy",
    desc: "Detect PII collection without consent, plaintext password storage, cross-border data transfer risks, and data retention violations, all mapped to specific DPDPA sections.",
    color: "text-violet-400",
    neon: "neon-violet",
    border: "border-violet-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(139,92,246,0.2)]",
    bg: "bg-violet-500/5",
  },
  {
    icon: Skull,
    title: "Dark Web Monitoring",
    category: "SOC",
    desc: "Continuously scans breach databases and dark web sources for leaked credentials, passwords, and data dumps matching your domains. Get alerted before attackers use your leaked data.",
    color: "text-red-400",
    neon: "neon-red",
    border: "border-red-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(239,68,68,0.2)]",
    bg: "bg-red-500/5",
  },
  {
    icon: Activity,
    title: "Security KPI Dashboard",
    category: "Metrics",
    desc: "Real-time security metrics: MTTD, MTTR, vulnerability density per KLOC, sandbox pass rate, adversarial win rate, resolution rate. 7-day trends with severity breakdowns.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: Radar,
    title: "Attack Surface Management",
    category: "Discovery",
    desc: "Continuously discover exposed services, open ports, and missing security headers on your live targets. Real-time risk assessment with per-endpoint exposure tracking.",
    color: "text-cyan-400",
    neon: "neon-cyan",
    border: "border-cyan-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(6,182,212,0.2)]",
    bg: "bg-cyan-500/5",
  },
  {
    icon: Network,
    title: "Data Exfiltration Defense",
    category: "Defense",
    desc: "Inject canary tokens into your data and monitor for exfiltration. Deploy honeypot endpoints to trap attackers. Real-time data flow monitoring detects suspicious outbound transfers.",
    color: "text-rose-400",
    neon: "neon-rose",
    border: "border-rose-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(244,63,94,0.2)]",
    bg: "bg-rose-500/5",
  },
  {
    icon: ScanLine,
    title: "Web Scraping Audit Engine",
    category: "Audit",
    desc: "Dual-mode (lightweight + browser) scraping engine with PII sanitization. Extract structured data from any URL, detect leaked credentials in responses, and generate integrity-hashed audit trails.",
    color: "text-violet-400",
    neon: "neon-violet",
    border: "border-violet-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(139,92,246,0.2)]",
    bg: "bg-violet-500/5",
  },
  {
    icon: GitBranch,
    title: "CI/CD Integration",
    category: "DevSecOps",
    desc: "Trigger scans from GitHub Actions, GitLab CI, or Jenkins. Merge-blocking when critical vulnerabilities are found. PR comments with patch suggestions. Full DevSecOps pipeline integration.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: AlertTriangle,
    title: "AI Attack Chain Synthesis",
    category: "Correlation",
    desc: "AI correlates individual vulnerabilities into multi-step attack chains. See how a low-severity XSS + a medium-severity IDOR + an info disclosure can chain into full account takeover.",
    color: "text-amber-400",
    neon: "neon-amber",
    border: "border-amber-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(245,158,11,0.2)]",
    bg: "bg-amber-500/5",
  },
  {
    icon: Workflow,
    title: "API Fuzzing + Business Logic Testing",
    category: "Testing",
    desc: "Stateful API fuzzing crashes endpoints with malformed inputs. Business logic testing detects price manipulation, privilege escalation, and race conditions. GraphQL + WebSocket testing included.",
    color: "text-orange-400",
    neon: "neon-orange",
    border: "border-orange-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(249,115,22,0.2)]",
    bg: "bg-orange-500/5",
  },
  {
    icon: Eye,
    title: "Executive Dashboard + Heatmap",
    category: "Visibility",
    desc: "Board-ready security posture dashboard with 8 KPIs, 7-day trends, top threats, and severity breakdowns. Per-codebase risk heatmap. Vuln correlation engine for root-cause analysis.",
    color: "text-cyan-400",
    neon: "neon-cyan",
    border: "border-cyan-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(6,182,212,0.2)]",
    bg: "bg-cyan-500/5",
  },
  {
    icon: Webhook,
    title: "Multi-Tenant RBAC + Integrations",
    category: "Platform",
    desc: "Organization-level multi-tenancy with admin/analyst/viewer roles. Integrate with Slack, Jira, GitHub, Splunk, ELK, PagerDuty. Webhook alerts + scheduled scans + full audit logging.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: Brain,
    title: "Guardian AI Assistant",
    category: "AI",
    desc: "Natural language interface to the entire platform. Ask 'what should I prioritize?' or 'which client has the most critical findings?' and get real answers from live data. Chat sidebar with context.",
    color: "text-violet-400",
    neon: "neon-violet",
    border: "border-violet-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(139,92,246,0.2)]",
    bg: "bg-violet-500/5",
  },
  {
    icon: Rocket,
    title: "Service Launcher + War Room",
    category: "Operations",
    desc: "Pick clients, pick a service (Scan/Test/Patch/Verify/Defend/Comply), launch. War Room fullscreen mode for wall projection with auto-cycling views. Clickable pipeline stages per client.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: FlaskConical,
    title: "Autonomous R&D Lab",
    category: "Self-Improving",
    desc: "Searches GitHub for open-source security tools, AI analyzes their code, performs gap analysis vs our modules, and generates optimization recommendations. Benchmark engine, protocol fuzzer, attack graph DAG, behavioral monitor, virtual patching, IaC remediation, rollback safeguards.",
    color: "text-violet-400",
    neon: "neon-violet",
    border: "border-violet-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(139,92,246,0.2)]",
    bg: "bg-violet-500/5",
  },
  {
    icon: Shield,
    title: "Virtual Patching + IaC Remediation",
    category: "Defense",
    desc: "Can't patch code immediately? Auto-generate WAF rules (ModSecurity, Cloudflare, iptables, Nginx) as virtual patches. Generate Terraform, Ansible, K8s, Docker manifests to patch at the deployment template level.",
    color: "text-rose-400",
    neon: "neon-rose",
    border: "border-rose-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(244,63,94,0.2)]",
    bg: "bg-rose-500/5",
    isNew: true,
  },
  // ── NEW: jaredrhod integration features ──────────────────────────────
  {
    icon: Mic,
    title: "Voice Command Center",
    category: "Voice AI",
    desc: "Talk to GuardianX. Push-to-talk, speech recognition, and text-to-speech built into the War Room. Say 'scan payment-handler.js' or 'what's the security posture?' — hands-free SOC operation. No API keys, runs in your browser.",
    color: "text-cyan-400",
    neon: "neon-cyan",
    border: "border-cyan-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(6,182,212,0.2)]",
    bg: "bg-cyan-500/5",
    isNew: true,
  },
  {
    icon: Hand,
    title: "Gesture Control",
    category: "Gesture AI",
    desc: "Control the War Room with your bare hands. Pinch to click, swipe to navigate tabs, open palm to scroll, fist to close. Webcam-based hand tracking via MediaPipe — no headset, no controllers. Built for wall projection in SOC environments.",
    color: "text-violet-400",
    neon: "neon-violet",
    border: "border-violet-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(139,92,246,0.2)]",
    bg: "bg-violet-500/5",
    isNew: true,
  },
  {
    icon: Cpu,
    title: "AI Neural Visualizer",
    category: "Visualization",
    desc: "A living circuit board that reacts to scans in real-time. Data pulses flow through traces as the AI analyzes code. Components flash red when vulnerabilities are found, green when patches are applied. Fullscreen immersive mode for war room projection.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
    isNew: true,
  },
  {
    icon: Brain,
    title: "AI Memory Vault",
    category: "Memory",
    desc: "The Guardian AI remembers. Every scan, every finding, every patch, every conversation — stored in a persistent memory vault. The AI can say 'Last time you scanned this codebase, we found 3 SQL injections. 2 are still unpatched.' No more starting fresh every session.",
    color: "text-amber-400",
    neon: "neon-amber",
    border: "border-amber-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(245,158,11,0.2)]",
    bg: "bg-amber-500/5",
    isNew: true,
  },
  {
    icon: Database,
    title: "Multi-Tenant RBAC + Organizations",
    category: "Platform",
    desc: "Organization-level data isolation with workspace switching. Admins see everything, analysts see only their own clients. Per-IP rate limiting, session revocation, 2FA/TOTP enforcement, audit logging on every sensitive action, and break-glass admin recovery.",
    color: "text-sky-400",
    neon: "neon-sky",
    border: "border-sky-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(14,165,233,0.2)]",
    bg: "bg-sky-500/5",
    isNew: true,
  },
  // ── NEW: 28 restored module catalog entries ─────────────────────────
  {
    icon: Bot,
    title: "Adversarial AI Self-Attack",
    category: "Self-Attack",
    desc: "Turn GuardianX's own AI against itself — an attacker persona probes the defender's patches for bypasses before they ship, iterating until the fix holds. Battle-tested code with zero human reviewer needed in the loop.",
    color: "text-red-400",
    neon: "neon-red",
    border: "border-red-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(239,68,68,0.2)]",
    bg: "bg-red-500/5",
    isNew: true,
  },
  {
    icon: Sparkles,
    title: "Agent X — Always-On AI Copilot",
    category: "AI",
    desc: "An ambient AI agent that watches your pipeline, suggests next actions, drafts patches, and answers security questions in natural language. Always on, always context-aware, and always learning from your activity feed.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
    isNew: true,
  },
  {
    icon: Drama,
    title: "APT Persona Engine",
    category: "Threat Sim",
    desc: "Replay real-world advanced persistent threats (Lazarus, Cozy Bear, FIN7) as AI-driven personas that attack your codebase with their documented TTPs. See whether your defenses would actually survive a real adversary.",
    color: "text-amber-400",
    neon: "neon-amber",
    border: "border-amber-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(245,158,11,0.2)]",
    bg: "bg-amber-500/5",
    isNew: true,
  },
  {
    icon: Bird,
    title: "Cryptographic Canary Tokens",
    category: "Defense",
    desc: "Plant tamper-evident canary tokens inside source, configs, and credentials. Any unauthorized access triggers an instant signed alert — proving exfiltration with cryptographic attribution before damage spreads.",
    color: "text-amber-400",
    neon: "neon-amber",
    border: "border-amber-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(245,158,11,0.2)]",
    bg: "bg-amber-500/5",
    isNew: true,
  },
  {
    icon: Users,
    title: "Security Commons — Bug Bounty",
    category: "Trust",
    desc: "Community-driven bug bounty board where external researchers submit findings, evidence is verified on-chain, and rewards are paid per confirmed vuln. Transparent disclosure, signed payouts, and ranked leaderboards.",
    color: "text-cyan-400",
    neon: "neon-cyan",
    border: "border-cyan-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(6,182,212,0.2)]",
    bg: "bg-cyan-500/5",
    isNew: true,
  },
  {
    icon: Orbit,
    title: "3D Threat Constellation",
    category: "Visibility",
    desc: "Your entire attack surface rendered as an interactive 3D constellation — codebases as stars, vulnerabilities as orbits, exploit chains as gravitational paths. Spin, zoom, and follow attack chains through space.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
    isNew: true,
  },
  {
    icon: Clapperboard,
    title: "Deepfake Phishing Simulator",
    category: "Social Eng",
    desc: "Generate synthetic voice and video deepfakes of your executives, then send them to staff as a controlled phishing drill. Train your team to spot AI-generated social engineering before the real attackers do.",
    color: "text-rose-400",
    neon: "neon-rose",
    border: "border-rose-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(244,63,94,0.2)]",
    bg: "bg-rose-500/5",
    isNew: true,
  },
  {
    icon: TrendingUp,
    title: "Predictive Threat Forecast",
    category: "Forecasting",
    desc: "AI projects your security posture 7/30/90 days ahead using CVE velocity, patch cadence, and exploit maturity trends. Forecast which libraries are about to catch fire and where to invest first.",
    color: "text-cyan-400",
    neon: "neon-cyan",
    border: "border-cyan-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(6,182,212,0.2)]",
    bg: "bg-cyan-500/5",
    isNew: true,
  },
  {
    icon: Shuffle,
    title: "Moving Target Defense",
    category: "Defense",
    desc: "Automatically rotate endpoints, secrets, ports, and WAF rules on a schedule so the attack surface is never the same twice. Attackers can't recon what keeps moving — defense by dynamism, not by walls.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
    isNew: true,
  },
  {
    icon: Coins,
    title: "Pay-Per-Vulnerability Marketplace",
    category: "Economics",
    desc: "Bounty-funded economics: each confirmed vuln has a market price, each accepted patch earns the fixer. Track payouts, ROI per finding, and bounty budgets per codebase. Security that pays for itself.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
    isNew: true,
  },
  {
    icon: Terminal,
    title: "AI Prompt Injection Scanner",
    category: "AI Security",
    desc: "Audit your LLM apps for prompt injection, jailbreaks, data exfiltration, and tool-misuse paths. Tests system prompt integrity, defense-in-depth instructions, and known attack patterns from the OWASP LLM Top 10.",
    color: "text-red-400",
    neon: "neon-red",
    border: "border-red-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(239,68,68,0.2)]",
    bg: "bg-red-500/5",
    isNew: true,
  },
  {
    icon: Atom,
    title: "Quantum-Readiness Scanner",
    category: "Post-Quantum",
    desc: "Inventory every cryptographic primitive in your codebase — RSA key sizes, ECC curves, hashes, TLS configs — and flag those vulnerable to Shor's and Grover's algorithms. Plan your migration to CRYSTALS-Kyber and Dilithium.",
    color: "text-violet-400",
    neon: "neon-violet",
    border: "border-violet-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(139,92,246,0.2)]",
    bg: "bg-violet-500/5",
    isNew: true,
  },
  {
    icon: ShieldCheck,
    title: "GuardianX Self-Security",
    category: "Self-Attack",
    desc: "GuardianX audits its own deployment — its own APIs, its own secrets, its own dependencies — and reports its own PostureScore in real-time. We eat our own dog food; if our posture drops, we tell you first.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
    isNew: true,
  },
  {
    icon: Rewind,
    title: "Time-Travel Posture Debugger",
    category: "Runtime",
    desc: "Step backward through your security posture timeline — see exactly when a vuln appeared, when it was patched, who pushed the change, and how the PostureScore moved minute by minute. Reproduce any past state for forensics.",
    color: "text-cyan-400",
    neon: "neon-cyan",
    border: "border-cyan-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(6,182,212,0.2)]",
    bg: "bg-cyan-500/5",
    isNew: true,
  },
  {
    icon: Glasses,
    title: "VR Threat Walkthrough",
    category: "Training",
    desc: "Walk through your codebase's vulnerabilities in VR — each vuln is a 3D room, exploit chains are corridors, patches are locked doors. Onboarding new analysts takes hours instead of weeks.",
    color: "text-violet-400",
    neon: "neon-violet",
    border: "border-violet-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(139,92,246,0.2)]",
    bg: "bg-violet-500/5",
    isNew: true,
  },
  {
    icon: EyeOff,
    title: "Zero-Knowledge Proofs",
    category: "Privacy",
    desc: "Prove compliance, patch status, and vuln remediation to auditors and partners WITHOUT revealing the underlying code or findings. zk-SNARK attestations — they learn only that you're compliant, nothing else.",
    color: "text-violet-400",
    neon: "neon-violet",
    border: "border-violet-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(139,92,246,0.2)]",
    bg: "bg-violet-500/5",
    isNew: true,
  },
  {
    icon: Siren,
    title: "DFIR Command Center",
    category: "IR",
    desc: "Digital Forensics & Incident Response workbench — ingest disk, memory, and network images, run YARA rules, build timeline reconstructions, and extract IOCs. Every artifact is hash-attested for chain of custody and court.",
    color: "text-red-400",
    neon: "neon-red",
    border: "border-red-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(239,68,68,0.2)]",
    bg: "bg-red-500/5",
  },
  {
    icon: Telescope,
    title: "SOC & DevSecOps Center",
    category: "SOC",
    desc: "Unified SOC dashboard — live alerts, SIEM correlation, case management, runbooks, and DevSecOps pipeline status. Correlate findings from SAST, DAST, runtime, and threat intel into single incidents.",
    color: "text-cyan-400",
    neon: "neon-cyan",
    border: "border-cyan-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(6,182,212,0.2)]",
    bg: "bg-cyan-500/5",
  },
  {
    icon: SlidersHorizontal,
    title: "Advanced Platform Features",
    category: "Platform",
    desc: "Feature flags, experimental modules, beta access, plugin marketplace, custom integrations registry, and the gateway to every bleeding-edge GuardianX capability before it ships to general availability.",
    color: "text-amber-400",
    neon: "neon-amber",
    border: "border-amber-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(245,158,11,0.2)]",
    bg: "bg-amber-500/5",
  },
  {
    icon: CreditCard,
    title: "Billing & Subscription",
    category: "Platform",
    desc: "Manage seats, plans (Free/Pro/Enterprise), add-ons, payment methods, and invoices. Track scan-minute usage, bounty payouts, and storage quotas. Stripe-backed, GST-compliant invoicing for India customers.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: Settings,
    title: "Settings & Configuration",
    category: "Platform",
    desc: "Workspace settings, branding, notification preferences, API keys, webhooks, SMTP config, SSO/OIDC, 2FA enforcement, session policies, and break-glass admin recovery. Every knob, in one place.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: UserCog,
    title: "User Management",
    category: "Platform",
    desc: "Invite, deactivate, and role-tag users (admin/analyst/viewer). Per-user MFA enforcement, session revocation, role inheritance, group policies, and a full audit log of every privileged action.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: PenLine,
    title: "Content Editor",
    category: "Platform",
    desc: "Edit landing page copy, feature cards, report templates, and email templates in a rich-text editor with live preview. Push to production with one click — no engineering required, no redeploy.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: Trophy,
    title: "Contributions & Leaderboard",
    category: "Platform",
    desc: "Open-source-style leaderboard ranking internal and external contributors by vulns found, patches accepted, and reviews completed. Streaks, badges, and bounty totals. Gamify your security team.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: LineChart,
    title: "User Activity Monitor",
    category: "Metrics",
    desc: "Real-time feed of every user action across the platform — scans launched, patches approved, findings triaged, logins. Spot idle accounts, heavy users, and suspicious activity patterns instantly.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: GitMerge,
    title: "Active Scan Pipelines",
    category: "Runtime",
    desc: "Live view of every running scan, patch, exploit, and verification job across all clients and codebases. Per-stage progress, queue depth, failure alerts, and one-click re-run. Your SOC's air-traffic control.",
    color: "text-amber-400",
    neon: "neon-amber",
    border: "border-amber-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(245,158,11,0.2)]",
    bg: "bg-amber-500/5",
  },
  {
    icon: Briefcase,
    title: "Client Engagements",
    category: "Platform",
    desc: "Multi-tenant client management — onboard clients, assign codebases, track per-client posture scores, SLA compliance, and engagement timelines. Per-client data isolation with full audit trail.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: FolderGit2,
    title: "Codebase Library",
    category: "SAST",
    desc: "Central library of all connected codebases — Git, upload, or paste. Per-codebase posture, vuln count, last scan, language breakdown, and dependency inventory. Clone, re-scan, or archive from one panel.",
    color: "text-sky-400",
    neon: "neon-sky",
    border: "border-sky-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(14,165,233,0.2)]",
    bg: "bg-sky-500/5",
  },
];

export { FileCode2, ShieldCheck, Crosshair, Swords, Bug } from "lucide-react";
