import {
  Bug,
  Crosshair,
  Swords,
  ScanLine,
  FileText,
  KeyRound,
  Gauge,
  Globe,
  Wand2,
  Heart,
  Link2,
  Gavel,
  Lock,
  Skull,
  Activity,
  Radar,
  Network,
  GitBranch,
  AlertTriangle,
  Workflow,
  Eye,
  Webhook,
  Brain,
  Rocket,
  FlaskConical,
  Shield,
  FileCode2,
  ShieldCheck,
  type LucideIcon,
} from "lucide-react";

export interface Feature {
  icon: LucideIcon;
  title: string;
  category: string;
  desc: string;
  color: string;
  neon: string;
  border: string;
  glow: string;
  bg: string;
}

export const FEATURES: Feature[] = [
  {
    icon: Bug,
    title: "AI Vulnerability Detection",
    category: "SAST",
    desc: "AI reads your source code and identifies real, exploitable vulnerabilities with CVE/CWE mapping, confidence scores, and the exact vulnerable snippet.",
    color: "text-red-400",
    neon: "neon-red",
    border: "border-red-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(239,68,68,0.2)]",
    bg: "bg-red-500/5",
  },
  {
    icon: Crosshair,
    title: "PoC Exploit Playground",
    category: "Exploit",
    desc: "For every vulnerability, the AI generates a working proof-of-concept exploit. Run it against the original code to prove the vuln is real, then against the patched code to prove the fix works.",
    color: "text-orange-400",
    neon: "neon-orange",
    border: "border-orange-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(249,115,22,0.2)]",
    bg: "bg-orange-500/5",
  },
  {
    icon: Swords,
    title: "Adversarial Red-Team Arena",
    category: "Self-Attack",
    desc: "After patching, a second AI persona attacks its own fix. If it finds a bypass, the defender iterates. Loop until the attacker concedes, the patch is battle-tested before human review.",
    color: "text-amber-400",
    neon: "neon-amber",
    border: "border-amber-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(245,158,11,0.2)]",
    bg: "bg-amber-500/5",
  },
  {
    icon: Crosshair,
    title: "RedAgent VAPT Engine",
    category: "DAST",
    desc: "Autonomous penetration testing against live targets. The AI crawls the app, plans category-appropriate attacks, fires real HTTP payloads, and confirms exploitation with full evidence.",
    color: "text-red-400",
    neon: "neon-red",
    border: "border-red-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(239,68,68,0.2)]",
    bg: "bg-red-500/5",
  },
  {
    icon: ScanLine,
    title: "Sensitive Data Exposure Scanner",
    category: "Secrets",
    desc: "Systematically detects exposed AWS/Stripe/GitHub keys, JWTs, private keys, passwords, SSNs, and credit cards. Probes 22+ known exposure paths. All samples redacted, proves the leak without exfiltrating.",
    color: "text-purple-400",
    neon: "neon-purple",
    border: "border-purple-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(168,85,247,0.2)]",
    bg: "bg-purple-500/5",
  },
  {
    icon: FileText,
    title: "Professional VAPT Reports",
    category: "Reporting",
    desc: "Generate a 15-page PDF VAPT report with front page, TOC, document control, executive summary, methodology, findings master table, detailed PoC evidence, compliance mapping, and cleanup certificate.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: KeyRound,
    title: "Encrypted Git Integration",
    category: "Credentials",
    desc: "Connect real private repos with AES-256-GCM encrypted credentials. Tokens are encrypted at rest, never shown again, never leaked in logs. Clone, explore, and import files for scanning.",
    color: "text-sky-400",
    neon: "neon-sky",
    border: "border-sky-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(14,165,233,0.2)]",
    bg: "bg-sky-500/5",
  },
  {
    icon: Gauge,
    title: "PostureScore",
    category: "Metrics",
    desc: "A 0–100 security credit score per codebase, computed from open vulns, sandbox pass rates, and adversarial win rates. Letter grades A–F. Trend over time. Exec-friendly at-a-glance posture.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: Globe,
    title: "Continuous Threat Intel",
    category: "Live Feed",
    desc: "Monitors live CVE disclosures via web search and cross-references them against your codebases. New 0-day for a lib you use? GuardianX flags it high-relevance before you've heard of it.",
    color: "text-cyan-400",
    neon: "neon-cyan",
    border: "border-cyan-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(6,182,212,0.2)]",
    bg: "bg-cyan-500/5",
  },
  {
    icon: Wand2,
    title: "AI Remediation Copilot",
    category: "Copilot",
    desc: "Inside every patch: ask the AI to explain the fix, generate an improved production-ready version, or produce a hardened defense-in-depth variant with input validation and rate limiting.",
    color: "text-violet-400",
    neon: "neon-violet",
    border: "border-violet-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(139,92,246,0.2)]",
    bg: "bg-violet-500/5",
  },
  {
    icon: Heart,
    title: "Self-Healing Runtime",
    category: "Runtime",
    desc: "Live runtime monitoring tracks which functions are vulnerable vs healed. One-click hot-swap deploys a patched function at runtime with zero downtime. Auto-heal when an attack is detected.",
    color: "text-rose-400",
    neon: "neon-rose",
    border: "border-rose-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(244,63,94,0.2)]",
    bg: "bg-rose-500/5",
  },
  {
    icon: Link2,
    title: "Cryptographic Patch Attestation",
    category: "Trust",
    desc: "Every approved patch is hash-chained into an immutable SHA-256 ledger. Tamper-evident: any modification to a past attestation breaks every subsequent hash. Enterprise-grade audit trail.",
    color: "text-teal-400",
    neon: "neon-teal",
    border: "border-teal-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(20,184,166,0.2)]",
    bg: "bg-teal-500/5",
  },
  {
    icon: Gavel,
    title: "DPDPA & Multi-Framework Compliance",
    category: "GRC",
    desc: "Map every finding to DPDPA 2023, GDPR, HIPAA, PCI-DSS, ISO 27001, and SOC 2. Track section-level compliance, generate audit reports, and auto-draft 72-hour breach notifications.",
    color: "text-purple-400",
    neon: "neon-purple",
    border: "border-purple-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(168,85,247,0.2)]",
    bg: "bg-purple-500/5",
  },
  {
    icon: Lock,
    title: "Data Privacy Scanner",
    category: "Privacy",
    desc: "Detect PII collection without consent, plaintext password storage, cross-border data transfer risks, and data retention violations, all mapped to specific DPDPA sections.",
    color: "text-indigo-400",
    neon: "neon-violet",
    border: "border-indigo-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(99,102,241,0.2)]",
    bg: "bg-indigo-500/5",
  },
  {
    icon: Skull,
    title: "Dark Web Monitoring",
    category: "SOC",
    desc: "Continuously scans breach databases and dark web sources for leaked credentials, passwords, and data dumps matching your domains. Get alerted before attackers use your leaked data.",
    color: "text-red-400",
    neon: "neon-red",
    border: "border-red-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(239,68,68,0.2)]",
    bg: "bg-red-500/5",
  },
  {
    icon: Activity,
    title: "Security KPI Dashboard",
    category: "Metrics",
    desc: "Real-time security metrics: MTTD, MTTR, vulnerability density per KLOC, sandbox pass rate, adversarial win rate, resolution rate. 7-day trends with severity breakdowns.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: Radar,
    title: "Attack Surface Management",
    category: "Discovery",
    desc: "Continuously discover exposed services, open ports, and missing security headers on your live targets. Real-time risk assessment with per-endpoint exposure tracking.",
    color: "text-cyan-400",
    neon: "neon-cyan",
    border: "border-cyan-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(6,182,212,0.2)]",
    bg: "bg-cyan-500/5",
  },
  {
    icon: Network,
    title: "Data Exfiltration Defense",
    category: "Defense",
    desc: "Inject canary tokens into your data and monitor for exfiltration. Deploy honeypot endpoints to trap attackers. Real-time data flow monitoring detects suspicious outbound transfers.",
    color: "text-rose-400",
    neon: "neon-rose",
    border: "border-rose-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(244,63,94,0.2)]",
    bg: "bg-rose-500/5",
  },
  {
    icon: ScanLine,
    title: "Web Scraping Audit Engine",
    category: "Audit",
    desc: "Dual-mode (lightweight + browser) scraping engine with PII sanitization. Extract structured data from any URL, detect leaked credentials in responses, and generate integrity-hashed audit trails.",
    color: "text-violet-400",
    neon: "neon-violet",
    border: "border-violet-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(139,92,246,0.2)]",
    bg: "bg-violet-500/5",
  },
  {
    icon: GitBranch,
    title: "CI/CD Integration",
    category: "DevSecOps",
    desc: "Trigger scans from GitHub Actions, GitLab CI, or Jenkins. Merge-blocking when critical vulnerabilities are found. PR comments with patch suggestions. Full DevSecOps pipeline integration.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: AlertTriangle,
    title: "AI Attack Chain Synthesis",
    category: "Correlation",
    desc: "AI correlates individual vulnerabilities into multi-step attack chains. See how a low-severity XSS + a medium-severity IDOR + an info disclosure can chain into full account takeover.",
    color: "text-amber-400",
    neon: "neon-amber",
    border: "border-amber-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(245,158,11,0.2)]",
    bg: "bg-amber-500/5",
  },
  {
    icon: Workflow,
    title: "API Fuzzing + Business Logic Testing",
    category: "Testing",
    desc: "Stateful API fuzzing crashes endpoints with malformed inputs. Business logic testing detects price manipulation, privilege escalation, and race conditions. GraphQL + WebSocket testing included.",
    color: "text-orange-400",
    neon: "neon-orange",
    border: "border-orange-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(249,115,22,0.2)]",
    bg: "bg-orange-500/5",
  },
  {
    icon: Eye,
    title: "Executive Dashboard + Heatmap",
    category: "Visibility",
    desc: "Board-ready security posture dashboard with 8 KPIs, 7-day trends, top threats, and severity breakdowns. Per-codebase risk heatmap. Vuln correlation engine for root-cause analysis.",
    color: "text-cyan-400",
    neon: "neon-cyan",
    border: "border-cyan-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(6,182,212,0.2)]",
    bg: "bg-cyan-500/5",
  },
  {
    icon: Webhook,
    title: "Multi-Tenant RBAC + Integrations",
    category: "Platform",
    desc: "Organization-level multi-tenancy with admin/analyst/viewer roles. Integrate with Slack, Jira, GitHub, Splunk, ELK, PagerDuty. Webhook alerts + scheduled scans + full audit logging.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: Brain,
    title: "Guardian AI Assistant",
    category: "AI",
    desc: "Natural language interface to the entire platform. Ask 'what should I prioritize?' or 'which client has the most critical findings?' and get real answers from live data. Chat sidebar with context.",
    color: "text-violet-400",
    neon: "neon-violet",
    border: "border-violet-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(139,92,246,0.2)]",
    bg: "bg-violet-500/5",
  },
  {
    icon: Rocket,
    title: "Service Launcher + War Room",
    category: "Operations",
    desc: "Pick clients, pick a service (Scan/Test/Patch/Verify/Defend/Comply), launch. War Room fullscreen mode for wall projection with auto-cycling views. Clickable pipeline stages per client.",
    color: "text-emerald-400",
    neon: "neon-emerald",
    border: "border-emerald-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(16,185,129,0.2)]",
    bg: "bg-emerald-500/5",
  },
  {
    icon: FlaskConical,
    title: "Autonomous R&D Lab",
    category: "Self-Improving",
    desc: "Searches GitHub for open-source security tools, AI analyzes their code, performs gap analysis vs our modules, and generates optimization recommendations. Benchmark engine, protocol fuzzer, attack graph DAG, behavioral monitor, virtual patching, IaC remediation, rollback safeguards.",
    color: "text-violet-400",
    neon: "neon-violet",
    border: "border-violet-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(139,92,246,0.2)]",
    bg: "bg-violet-500/5",
  },
  {
    icon: Shield,
    title: "Virtual Patching + IaC Remediation",
    category: "Defense",
    desc: "Can't patch code immediately? Auto-generate WAF rules (ModSecurity, Cloudflare, iptables, Nginx) as virtual patches. Generate Terraform, Ansible, K8s, Docker manifests to patch at the deployment template level.",
    color: "text-rose-400",
    neon: "neon-rose",
    border: "border-rose-500/40",
    glow: "hover:shadow-[0_0_24px_rgba(244,63,94,0.2)]",
    bg: "bg-rose-500/5",
  },
];

export { FileCode2, ShieldCheck, Crosshair, Swords, Bug } from "lucide-react";
